### ISSUE TITLE
Ert storage crashed with "Data not found"

### ISSUE THREAD

**Issue by berland** [equinor/ert#8975] opened 2024-10-16 06:07 UTC
### What happened? (You can include a screenshot if it helps explain)

Crash observed in logs:

`httpx.RequestError:  Please report this error and try restarting the application.{"detail":"Data not found"} from url: http://127.0.0.1:51831/ensembles/dbfd5dxxxxxxxxa-43c6-8f07-eff56007bbd2/records/aps_Below_top_XXXX31_XXX2/std_dev?z=0.`
            

More context:

```
Traceback (most recent call last):
File "/prog/res/komodo/2024.09.04-py38-rhel8/root/lib64/python3.8/site-packages/ert/gui/tools/plot/plot_window.py", line 220, in updatePlot
std_dev_images[ensemble.name] = self._api.std_dev_for_parameter(
File "/prog/res/komodo/2024.09.04-py38-rhel8/root/lib64/python3.8/site-packages/ert/gui/tools/plot/plot_api.py", line 268, in std_dev_for_parameter
self._check_response(response)
File "/prog/res/komodo/2024.09.04-py38-rhel8/root/lib64/python3.8/site-packages/ert/gui/tools/plot/plot_api.py", line 88, in _check_response
raise httpx.RequestError(
httpx.RequestError: Please report this error and try restarting the application.{"detail":"Data not found"} from url: http://127.0.0.1:51831/ensembles/dbfd5d0e-b79axxxxeff56007bbd2/records/aps_Below_top_XXX31_XXX2/std_dev?z=0.
```

            
            

### What did you expect to happen?

Ert should not crash like this. If user error, validate away the situation.

### Environment where bug has been observed

- [x] python 3.8
- [ ] python 3.9
- [ ] python 3.10
- [ ] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [x] rhel8
- [ ] local queue
- [x] lsf queue
- [ ] slurm queue
- [ ] openPBS queue

**Comment by frode-aarstad** [comment] 2024-12-13 07:24
Could not reproduce. Fixed in https://github.com/equinor/ert/commit/0da5c9c07cfe7932084ce4e59e73e50d5beaf42d

**Closed by frode-aarstad** 2024-12-13 07:24 UTC
Labels: bug
