### ISSUE TITLE
Unexpected job status type after running job: JOB_QUEUE_DO_KILL_NODE_FAILURE

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1566] opened 2021-04-20 09:10 UTC
**Describe the bug**
Running `ert --enable-new-storage` from komodo 2021.03.01 produced the following error:

```python
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/prog/res/komodo/2021.03.01-py36-rhel7/root/lib64/python3.6/site-packages/res/job_queue/job_queue_node.py", line 185, in _job_monitor
    self.status
AssertionError: Unexpected job status type after running job: JOB_QUEUE_DO_KILL_NODE_FAILURE
```

**To Reproduce**
TBD

**Expected behavior**
Not crash

**Enviromment**
 - OS: RHEL7
 - ERT/Komodo Release: 2021.03.01
 - Python version: 3,6
 - Remote/HPC execution involved: yes

**Additional context**

**Comment by markusdregi** [comment] 2021-04-26 13:54
@sondreso: Update on steps to reproduce?

**Comment by sondreso** [comment] 2021-04-26 14:51
I don't have it. Originally reported by: @eivindsm. 

Think one could start this issue by looking at why JOB_QUEUE_DO_KILL_NODE_FAILURE is unexpected (as it is a valid queue status type), and also see what scenarios in the driver that produces this error. I suspect it might not be very easy to reproduce.

**Comment by joakim-hove** [comment] 2021-04-26 14:57
https://github.com/equinor/libres/pull/966

**Comment by markusdregi** [comment] 2021-04-27 11:11
I'm suspecting that we might be able to reproduce it by launching a run and using either `bkill`, or more likely the "HPC portal" to shut down certain compute nodes...

**Comment by oyvindeide** [comment] 2022-12-14 13:59
Since there has not been any updates here, and presumably it has not been reproduced I will close this, if seen again or there is a way to reproduce, feel free to reopen,.

**Closed by oyvindeide** 2022-12-14 13:59 UTC
Labels: bug
