### ISSUE TITLE
Confusing error message on missing observation files

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#2000] opened 2021-09-05 07:43 UTC
**Describe the bug**
If observation related files are missing an error message related to changes in interpretation of observation paths in ERT 2.3 are displayed. Since ERT <2.3 users are probably not existing at all and for sure not internally, the error message should be replaced by one stating which files are missing instead.

**To Reproduce**
1. Install ERT
2. Open the poly example (`cd test-data/local/poly_example`)
3. Delete the observation values (`rm poly_obs_data.txt`)
4. Try to run ERT (`ert test_run poly.ert`)

**Expected behaviour**
I would expect an error message stating something along the lines of `The configured OBS_FILE "poly_obs_data.txt" is missing.`

**Terminal dump**
```
(ert-env39) markus$ rm poly_obs_data.txt 
(ert-env39) markus$ ert test_run poly.ert 
**********************************************************************
* In ert version 2.3 we have changed how filepaths are interpreted   *
* in the observation file. When using the keywords OBS_FILE,         *
* ERROR_COVAR and INDEX_FILE in the category GENERAL_OBSERVATION     *
* the filenames will be interpreted relative to the main observation *
* file.                                                              *
*                                                                    *
* Please update the OBS_FILE, ERROR_COVAR and INDEX_FILE keywords    *
* by removing the path to the main observation file.                 *
**********************************************************************
```

**Enviromment**
Reproduced both on-premise and on my MacBook.
 - OS: RHEL7 and MacOS
 - ERT/Komodo Release: Komodo@2021.09 and GitHub@main
 - Python version: 3.6 and 3.9
 - Remote/HPC execution involved: no

**Comment by sondreso** [comment] 2021-09-07 06:32
Duplicate of https://github.com/equinor/ert/issues/938

**Closed by sondreso** 2021-09-07 06:32 UTC
Labels: bug
