### ISSUE TITLE
Flaky test, test_observation_times::test_small_time_mismatches_are_ignored

### ISSUE THREAD

**Issue by berland** [equinor/ert#7587] opened 2024-04-08 06:37 UTC
Occured in https://github.com/equinor/ert/actions/runs/8553582418/job/23475634448?pr=7552
```
FAILED tests/integration_tests/test_observation_times.py::test_small_time_mismatches_are_ignored - AssertionError: assert 'Experiment completed' in ''
 +  where '' = <built-in method getvalue of _io.StringIO object at 0x7f3ba8735700>()
 +    where <built-in method getvalue of _io.StringIO object at 0x7f3ba8735700> = <_io.StringIO object at 0x7f3ba8735700>.getvalue
Falsifying example: test_small_time_mismatches_are_ignored(
    tmp_path_factory=TempPathFactory(_given_basetemp=PosixPath('/tmp/pytest-of-runner/pytest-0/popen-gw2'), _trace=<pluggy._tracing.TagTracerSub object at 0x7f3bb12a20a0>, _basetemp=PosixPath('/tmp/pytest-of-runner/pytest-0/popen-gw2'), _retention_count=3, _retention_policy='all'),
    responses_observation={'responses': [(Smspec(
           nx=int32(10),
           ny=int32(4),
           nz=int32(4),
           restarted_from_step=0,
           num_keywords=2,
           restart='RVYDFMNE',
           keywords=['TIME    ', 'FOPR'],
           well_names=[':+:+:+:+', 'FCVHBISY'],
           lgrs=None,
           numlx=None,
           numly=None,
           numlz=None,
           region_numbers=[-32676, int32(106)],
           units=['HOURS   ', 'HOURS'],
           start_date=Date(day=1, month=1, year=1969, hour=0, minutes=0, micro_seconds=0),
           use_names=True,
           intehead=SmspecIntehead(
               unit=UnitSystem.METRIC,
               simulator=Simulator.INTERSECT,
           ),
       ),
       Unsmry(steps=[SummaryStep(seqnum=0, ministeps=[SummaryMiniStep(mini_step=0, params=[0.0, 5.4072517e+16]), SummaryMiniStep(mini_step=1, params=[121488.0, 211106230000000.0])])])),
      (Smspec(
           nx=int32(1),
           ny=int32(7),
           nz=int32(9),
           restarted_from_step=0,
           num_keywords=2,
           restart='WDQTLACB',
           keywords=['TIME    ', 'FOPR'],
           well_names=[':+:+:+:+', 'HELVCVPG'],
           lgrs=None,
           numlx=None,
           numly=None,
           numlz=None,
           region_numbers=[-32676, int32(24)],
           units=['HOURS   ', 'SM3'],
           start_date=Date(day=1, month=1, year=1969, hour=0, minutes=0, micro_seconds=0),
           use_names=False,
           intehead=SmspecIntehead(
               unit=UnitSystem.METRIC,
               simulator=Simulator.ECLIPSE_300,
           ),
       ),
       Unsmry(steps=[SummaryStep(seqnum=0, ministeps=[SummaryMiniStep(mini_step=0, params=[0.0, 67335.0])]), SummaryStep(seqnum=1, ministeps=[SummaryMiniStep(mini_step=1, params=[121488.0, 2261717200000000.0])])]))],
     'observation': SummaryObservation(name='FOPR_OBSERVATION', error=10.0, value=3379495867778279.0, key='FOPR', error_min=10.0, error_mode=<ErrorMode.REL: 1>, days=None, hours=None, restart=None, date='1982-11-11')},
    std_cutoff=1.192092896e-07,
    enkf_alpha=4.0,
    epsilon=0.0,
)
Explanation:
    These lines were always and only run by failing examples:
        /home/runner/work/ert/ert/tests/integration_tests/run_cli.py:17
        /home/runner/work/ert/ert/tests/integration_tests/test_observation_times.py:113
        /home/runner/work/ert/ert/tests/integration_tests/test_observation_times.py:119
        /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/calendar.py:123
        /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/copy.py:140
        (and 7 more with settings.verbosity >= verbose)

You can reproduce this example by temporarily adding @reproduce_failure('6.100.0', b'AXicYxTi4mLgZGZmZWUSZWfkEJIwzxQUlWBm5eFlYWRgZmQAggNSq4CAAQwOQCgGNg42dhZuUSZRfjZxMWYBYW4GJqBaRgYYYGRnB9McnKy83AzMcHEGLnQmD+Miox0sz4Gsg4n5ixsYkAELAwC0Nww5') as a decorator on your test case
= 1 failed, 1892 passed, 18 skipped, 1 xfailed, 4106 warnings in 938.45s (0:15:38) =
```

**Comment by jonathan-eq** [comment] 2024-04-09 05:49
Unassigning myself as I got assigned to other, more critical bugs

**Comment by eivindjahren** [comment] 2024-04-23 12:38
Could not reproduce this failure so I assume it was fixed in 7612

**Closed by eivindjahren** 2024-04-23 12:38 UTC
Labels: flaky-test
