### ISSUE TITLE
Run a nightly build with address sanitizer

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#574] opened 2019-11-26 13:56 UTC
In order to catch memory errors earlier and with less work, we should compile both libres and libecl with address sanitizer and run all tests of ert, libres and libecl.

**Comment by dotfloat** [comment] 2019-12-10 12:39
I've determined that this isn't viable to do at the moment. libasan doesn't recognise pymalloc and changing to libc malloc with PYTHONMALLOC is a python 3 feature.

We may reconsider in the future when we use py3 in komodo.

**Comment by mortalisk** [comment] 2019-12-17 09:16
Do we need komodo for anything? Can we run a local build?

**Comment by dotfloat** [comment] 2019-12-17 13:48
We can use address sanitiser locally, but `pytest` exits with exit code 1 because it doesn't garbage collect before quitting. This is not a bug, but it makes it so we can't automate it at the moment.

**Comment by markusdregi** [comment] 2021-04-19 19:46
@dotfloat and @mortalisk: We now use Python3 in komodo. Is this something we could look into at some point or do we want to close the issue?

**Comment by sondreso** [comment] 2021-12-22 13:02
Closing due to inactivity and low relevance

**Closed** 2021-12-22 13:02 UTC
Labels: enhancement, EOL Python 2
