### ISSUE TITLE
job_dispatch may leave zombie processes on the compute nodes

### ISSUE THREAD

**Issue by berland** [equinor/ert#5562] opened 2023-06-12 10:54 UTC
**Describe the bug**
In certain situations, `job_dispatch.py` leaves zombie processes (`<defunct>`) on the compute nodes. When that happens, the compute node is not freed up to the compute cluster, and costs keep running.

**To reproduce**
TBA

**Expected behaviour**
job_dispatch should exit no matter what kind of error occurs.

**Screenshots**

**Environment**
 - OS: [e.g. RHEL7]
 - ERT/Komodo release: [e.g. 2.18 or 2020.12.00]
 - Python version
 - Remote/HPC execution involved: [yes|no]

**Additional context**

**Comment by xjules** [comment] 2023-06-19 10:46
Potential duplicate of https://github.com/equinor/ert/issues/5549.

**Closed by xjules** 2023-06-19 10:46 UTC
Labels: bug
