### ISSUE TITLE
Event loop is closed exception when ctrl-c'ing ensemble_experiment

### ISSUE THREAD

**Issue by berland** [equinor/ert#7701] opened 2024-04-18 13:17 UTC
* Run poly_example (maybe LSF queue is needed)
* Let poly_eval.py sleep for 100 seconds
* Hit ctrl-c when the realizations are running

The terminal ends with:
```
    --> Running forecast for iteration: 0

    1/1 |                                                             |   0% Running time: 8 seconds

    ■ Waiting          0/10
    ■ Pending          0/10
    ■ Running         10/10
    ■ Failed           0/10
    ■ Finished         0/10
    ■ Unknown          0/10

^C
Killing simulations...
Experiment failed! All realizations failed!

Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7f3592a0ca60>
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/base_subprocess.py", line 126, in __del__
    self.close()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/unix_events.py", line 536, in close
    self._close(None)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/unix_events.py", line 560, in _close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

This RuntimeError should not occur.

**Comment by berland** [comment] 2024-04-18 13:17
Possibly the same root cause as #7642

**Comment by berland** [comment] 2024-04-18 13:22
(this is flaky and not always reproducible on LSF)

**Comment by jonathan-eq** [comment] 2024-04-23 11:23
This one is difficult to reproduce.

**Comment by xjules** [comment] 2024-07-26 07:51
Could not reproduce it. Everything was shutdown correctly.
NB: Running on bleeding with the new async ensemble evaluator and scheduler.

**Comment by xjules** [comment] 2024-08-06 13:25
Since, the error has not appeared again, closing this issue.

**Closed by xjules** 2024-08-06 13:25 UTC
