### ISSUE TITLE
GUI not appropriately updating outside ensemble evaluator runs

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1680] opened 2021-05-14 08:28 UTC
**Describe the bug**
After https://github.com/equinor/ert/issues/1675, tracking progress using an ensemble evaluator will not produce updates during updates and uploads to storage. So if uploading data takes long, the GUI will appear "frozen".

**To Reproduce**
1. `ert gui --enable-new-storage test-data/local/poly_example/poly.ert`
2. Run smoother for 100 reals

**Expected behavior**
Expected to see "Uploading data..."

**Actual behaviour**
Did not see that

**Additional context**
Should probably not be solved prior to #1250

**Comment by oyvindeide** [comment] 2023-12-05 08:36
Closing this as no longer possible to reproduce due to removing new storage option.

**Closed by oyvindeide** 2023-12-05 08:36 UTC
Labels: ensemble-evaluator, improvement
