### ISSUE TITLE
Flaky tests/unit_tests/storage/migration/test_block_fs_snake_oil.py::test_migration_failure 

### ISSUE THREAD

**Issue by xjules** [equinor/ert#8656] opened 2024-09-05 13:48 UTC
```sh
FAILED tests/unit_tests/storage/migration/test_block_fs_snake_oil.py::test_migration_failure - assert 2 == 1
 +  where 2 = len([<LogRecord: asyncio, 30, /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/unix_events.py, 1334, "Loop %r that handles pid %r is closed">, <LogRecord: ert.storage.migration.block_fs, 30, /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/ert/storage/migration/block_fs.py, 266, "Exception occurred during migration of BlockFs case 'default_0': 'The key:SNAKE_OIL_PARAM is not in the ensemble configuration'">])
 +    where [<LogRecord: asyncio, 30, /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/unix_events.py, 1334, "Loop %r that handles pid %r is closed">, <LogRecord: ert.storage.migration.block_fs, 30, /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/ert/storage/migration/block_fs.py, 266, "Exception occurred during migration of BlockFs case 'default_0': 'The key:SNAKE_OIL_PARAM is not in the ensemble configuration'">] = <_pytest.logging.LogCaptureFixture object at 0x7f4014d6c7f0>.records
= 1 failed, 2013 passed, 22 skipped, 4543 warnings, 1 rerun in 242.66s (0:04:02) =
```

https://github.com/equinor/ert/actions/runs/10721062383/job/29728703519?pr=8649

**Comment by jonathan-eq** [comment] 2024-09-16 12:16
This seems to be an asyncio error, with a loop closing prematurely

**Comment by jonathan-eq** [comment] 2024-09-16 12:53
Very difficult to reproduce.
Will put back to Todo, and close it if not seen again for a while.

**Comment by eivindjahren** [comment] 2024-09-25 12:18
No longer relevant as block_fs is removed

**Closed by eivindjahren** 2024-09-25 12:18 UTC
Labels: bug, flaky-test
