### ISSUE TITLE
Proper signal handling and exit code

### ISSUE THREAD

**Issue by verveerpj** [equinor/ert#3134] opened 2022-03-21 15:20 UTC
**Issue**
Currently there are different points in the code where signal handlers are set or should be set:

- In `ert_shared.services`, handlers are set up for `signal.SIGINT` and `signal.SIGTERM` which are used to clean up files.
- An exit handler is set on `signal.SIGINT` to report termination of webviz by Ctlr-C.
- Currently, ctrl-C is not handled properly by `ert3` (issue: #3099), which implies another handler needs to be set for `ert3 run`. 

To properly handle these signals, it should be possible to set multiple handlers. The code for installing/uninstalling handlers should be centralized.

**Question:**
Currently the signal handlers used in `_base_service.py` raise an `OSError` after handling the signal. Why is this?

**Comment by oyvindeide** [comment] 2022-11-09 14:01
Related to/duplicate of: https://github.com/equinor/ert/issues/4006

**Closed by oyvindeide** 2022-11-09 14:01 UTC
