### ISSUE TITLE
Starting ert api / ert vis 

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#1274] opened 2021-01-05 12:02 UTC
We need to figure out what to do in following scenarios.

- Start ert vis / ert api outside of ert project. Currently this succeeds and start with an empty database.
- What to do when a user writes `ert api` while ert api is currently running on some (maybe non-local) machine
- What to do when a user writes `ert vis` while ert vis is currently running on some (maybe non-local) machine

**Comment by dotfloat** [comment] 2021-01-07 12:11
> * Start ert vis / ert api outside of ert project. Currently this succeeds and start with an empty database.

I think a simple check for `ert_storage.db` should suffice. We don't want to start ert vis / api where it doesn't make sense.

> * What to do when a user writes `ert api` while ert api is currently running on some (maybe non-local) machine

I like my own service-based approach, where these services are started on demand:
1. If there is no `storage_server.json`, start `ert api`
2. Otherwise, fail gracefully (`sys.exit(0)`). In the future, maybe open a browser pointing to `/docs`.

> * What to do when a user writes `ert vis` while ert vis is currently running on some (maybe non-local) machine

1. If there is no `storage_server.json`, start `ert api` in the background
2. If there is no `webviz-ert_server.json`, start `ert vis` and open the browser
3. If `webviz-ert_server.json` exists, fail gracefully and open the browser

The problem with this is that if:
Alice does `ert api`. Bob does `ert vis` also. Now Bob is connected to Alice's instance. If Alice closes her terminal, Bob's visualisation loses connection to storage, with no obvious way to re-enable the connection. There are ways to resolve this (eg. Bob's server will figure out that the storage is down and start it itself), but I reckon it's not worth the time and potential mountains of bugs.

Also, this doesn't handle race conditions at all.

**Comment by oysteoh** [comment] 2021-02-09 14:35
Is this ( sharing a database ) at all feasible now with the moving of the databasefile to `tmp` directory? I guess reading is fine, but no writing?

**Comment by markusdregi** [comment] 2021-04-26 11:01
@oysteoh: Is this issue still up to date?

**Comment by oysteoh** [comment] 2021-04-26 11:03
> @oysteoh: Is this issue still up to date?

No, i guess not. And at least not with the approach of doing central postgres. @dotfloat  do you have any thoughts about this in the newnew storage? Should we just close this issue, or adjust it?

**Comment by dotfloat** [comment] 2021-04-26 14:16
We still need this functionality and have someone with working braincells to figure out what the correct thing to do is. The issue is difficult in terms of design decisions and not technical implementation, so I am just hoping someone will come along and solve all of my problems in a satisfying way.

We can discuss this on the next standup / planning.

**Comment by markusdregi** [comment] 2021-04-27 11:08
Perfect! Thanks :)

**Comment by dotfloat** [comment] 2021-05-21 10:31
Closing due to overly complicated solution to a problem that we don't have right now and probably won't have in the future.

**Closed by dotfloat** 2021-05-21 10:31 UTC
Labels: storage
