### ISSUE TITLE
Handle sending messages to closed socket

### ISSUE THREAD

**Issue by DanSava** [equinor/ert#1307] opened 2021-01-21 08:59 UTC
If a message is sent to a webscket connection that has been closed the sending code will raise a 

```
ConnectionClosedOK('code = 1000 (OK), no reason')
```

Identify why messages are sent to closed socket connections and avoid raising the exception

**Comment by sondreso** [comment] 2021-03-25 09:12
Can be seen for the ert3 tests on Github actions

**Comment by markusdregi** [comment] 2021-03-25 09:15
Is also reproducible consistently on MacOS locally

**Comment by jondequinor** [comment] 2021-03-29 08:28
It wasn't very annoying to debug, it became clear quite early that the two monitors were one and the same, but on two separate connections. Spawned issue https://github.com/equinor/ert/issues/1538 and provided a workaround in the meantime, because I don't think there's a real fix for this until we have defined a protocol. A protocol would for example state that a monitor should only open one connection and send signals over that connection, as well as read messages from the EE. But it is unclear in what order things should happen.

Hopefully we will have migrated to a proper message broker before then. :cross_fingers:

**Closed** 2021-03-29 10:23 UTC
Labels: annoying_to_debug, user request
