### ISSUE TITLE
Move encoding functionality into the Record base class

### ISSUE THREAD

**Issue by verveerpj** [equinor/ert#1873] opened 2021-07-15 09:29 UTC
Currently we are moving towards a record implementation consisting of a `Record` base class, and `NumericalRecord` and `BlobRecord` classes (PR #1857 ). In various places in the code, in particular the transmitter code, we are checking for the concrete record type, to implement type-dependent functionality, for instance because they are in need of different encodings (i.e. json vs binary).

This issue proposes the following:
- Investigate if it is possible to move a minimal set of functionality to the concrete classes, with an abstract interface, such that the transmitters can be rewritten using base record methods only. 
- Scan the code for other uses of concrete records and see if they can be abstracted by moving functionality into the record classes.

**Comment by DanSava** [comment] 2021-07-27 10:07
It is not really clear to me what encoding functionality is referring to. Is it just getting the encoding type for each of the record instances:

For example:
* `NumericalRecord` -> `application/json` 
and 
* `BlobRecord` -> `application/octet-stream`

**Comment by DanSava** [comment] 2021-07-27 10:10
Initially, I thought it was referring to functionality that is used to encode the record using the different instances of RecordTransmitters, and that functionality that is common for all transmitters should be moved in the base RecordTransmitter class. 

And now I am a bit worried this is not what this issue is about

**Comment by verveerpj** [comment] 2021-07-27 10:16
Sorry if the issue is unclear. The issue was about trying to move functionality into the base Record class, so that we can avoid as much as possible checking the type of the record with `isinstance`. One option would indeed be to make base method that serializes the data to an appropriate format, either json or byte array. Of course, you still would have to have logic to do the appropriate thing with those (e.g. text file vs binary file). Therefore, I have to admit that I am not too sure if that abstraction is really helpful...

**Comment by DanSava** [comment] 2021-07-27 10:57
Ok but that sounds more of a duplicate of #1555

**Comment by verveerpj** [comment] 2021-07-27 11:01
It seems #1555 is about transmitters, while this issue was about the records, with maybe a broader scope, but yes, it seems they overlap a lot, at least...

**Comment by DanSava** [comment] 2021-07-27 11:05
I am guessing it is possible to add functionality in the Record base class to read and write to a file that will reduce some code and also maybe simplify some stuff, but is that a good idea?  This kind of breaks my idea of what a Record was supposed to be, which is a simple data class that should not be anything more than a fancy data container.

**Comment by verveerpj** [comment] 2021-07-27 11:11
> I am guessing it is possible to add functionality in the Record base class to read and write to a file that will reduce some code and also maybe simplify some stuff, but is that a good idea? This kind of breaks my idea of what a Record was supposed to be, which is a simple data class that should not be anything more than a fancy data container.

That is a valid point, so maybe we need to discuss that a bit more with Markus and/or Sondre.

**Comment by jondequinor** [comment] 2021-07-27 17:32
I'd also like to point to the End-to-end principle which says that 

> functions placed at low levels of a system may be redundant or of little value when compared with the cost of providing them at that low level.

Since both Record and RecordTransmitters are currently undergoing a lot of revision, moving stuff down the abstraction chain might cause some later grief. 

And I second Dan's sentiment.

**Comment by DanSava** [comment] 2021-07-28 05:34
Also had a discussion with @sondreso regarding this issue and the consensus was that it might not be the right time to add any encoding functionality to the record base class. 

Closing the current issue.

**Closed by DanSava** 2021-07-28 05:34 UTC
Labels: enhancement
