### ISSUE TITLE
Changing active realizations to ensembles with STATE_PARENT_FAILURE causes simulations to hang

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#4979] opened 2023-02-28 11:10 UTC
**Describe the bug**
Running realizations which has `STATE_PARENT_FAILURE` causes the simulations dialog to hang and not complete.

**To reproduce**
Steps to reproduce the behaviour:
1. Edit `test-data/poly_example/poly_eval.py` to include the following:
```python
import json
import random

...

if __name__ == "__main__":
    coeffs = _load_coeffs("coeffs.json")
    output = [_evaluate(coeffs, x) for x in range(10)]
    if random.randint(0, 1) == 0:
        raise ValueError()
    with open("poly_0.out", "w", encoding="utf-8") as f:
        f.write("\n".join(map(str, output)))
```
So that it randomly fails some times.
2. Run `ert gui tests-data/poly-example/poly.ert`
3. Run an example experiment
4. Click on run run analysis and run with target case "iter-1"
5. Run ensemble experiment on the newly created case, but change the `Active realizations` to include one of the realizations that failed on the parent ensemble (this has state = STATE_PARENT_FAILURE in manage_casese->case info)

![image](https://user-images.githubusercontent.com/44577479/221836703-0ca2ef2a-1ccb-4819-aa9d-bf04e3c03fd4.png)

**Expected behaviour**
Should give a warning saying that we are attempting to run something that will fail, but just hangs instead

**Comment by kvashchuka** [comment] 2023-10-13 11:20
I tried to reproduce with the latest ert, and it does no hang! It finishes with some failed realizations

**Comment by kvashchuka** [comment] 2023-10-17 09:50
Closing the issue as was not able to reproduce

**Closed by kvashchuka** 2023-10-17 09:50 UTC
Labels: bug
