### ISSUE TITLE
`test_failing_job_cli_error_messsage` fails on komodo

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#6905] opened 2024-01-05 07:36 UTC
```
[gw3] linux -- Python 3.8.18 /mnt/scratch/f_scout_ci/actions-runner-04/_temp/test-kenv/root/bin/python

    @pytest.mark.scheduler()
    @pytest.mark.integration_test
    @pytest.mark.usefixtures("copy_poly_case", "try_queue_and_scheduler", "monkeypatch")
    def test_failing_job_cli_error_message():
        # modify poly_eval.py
        with open("poly_eval.py", mode="a", encoding="utf-8") as poly_script:
            poly_script.writelines(["    raise RuntimeError('Argh')"])
    
        args = Mock()
        args.config = "poly_high_min_reals.ert"
        parser = ArgumentParser(prog="test_main")
        parsed = ert_parser(
            parser,
            [TEST_RUN_MODE, "poly.ert"],
        )
        expected_substrings = [
            "Realization: 0 failed after reaching max submit (2)",
            "job poly_eval failed",
            "Process exited with status code 1",
            "Traceback",
            "raise RuntimeError('Argh')",
            "RuntimeError: Argh",
        ]
        try:
>           run_cli(parsed)

/mnt/scratch/f_scout_ci/actions-runner-04/_temp/test_root/tests/integration_tests/cli/test_integration_cli.py:459: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/prog/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/cli/main.py:143: in run_cli
    model.reraise_exception(ErtCliError)
/prog/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/run_models/base_run_model.py:312: in reraise_exception
    raise exctype(self.getFailMessage()).with_traceback(
/prog/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/run_models/base_run_model.py:249: in startSimulations
    run_context = self.run_experiment(
/prog/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/run_models/single_test_run.py:38: in run_experiment
    return self.runSimulations__(
/prog/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/run_models/ensemble_experiment.py:86: in runSimulations__
    self._evaluate_and_postprocess(prior_context, evaluator_server_config)
/prog/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/run_models/base_run_model.py:527: in _evaluate_and_postprocess
    self.checkHaveSufficientRealizations(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

num_successful_realizations = 0, _ = 1

    @staticmethod
    def checkHaveSufficientRealizations(
        num_successful_realizations: int, _: int
    ) -> None:
        # Should only have one successful realization
        if num_successful_realizations != 1:
>           raise ErtRunError("Experiment failed!")
E           ert.cli.main.ErtCliError: Experiment failed!

/prog/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/ert/run_models/single_test_run.py:33: ErtCliError

During handling of the above exception, another exception occurred:

    @pytest.mark.scheduler()
    @pytest.mark.integration_test
    @pytest.mark.usefixtures("copy_poly_case", "try_queue_and_scheduler", "monkeypatch")
    def test_failing_job_cli_error_message():
        # modify poly_eval.py
        with open("poly_eval.py", mode="a", encoding="utf-8") as poly_script:
            poly_script.writelines(["    raise RuntimeError('Argh')"])
    
        args = Mock()
        args.config = "poly_high_min_reals.ert"
        parser = ArgumentParser(prog="test_main")
        parsed = ert_parser(
            parser,
            [TEST_RUN_MODE, "poly.ert"],
        )
        expected_substrings = [
            "Realization: 0 failed after reaching max submit (2)",
            "job poly_eval failed",
            "Process exited with status code 1",
            "Traceback",
            "raise RuntimeError('Argh')",
            "RuntimeError: Argh",
        ]
        try:
            run_cli(parsed)
        except ErtCliError as error:
            for substring in expected_substrings:
>               assert substring in f"{error}"
E               AssertionError: assert 'Realization: 0 failed after reaching max submit (2)' in 'Experiment failed!\n'
```

**Comment by xjules** [comment] 2024-01-05 08:11
Closing this one: duplicate of https://github.com/equinor/ert/issues/6863

**Closed by xjules** 2024-01-05 08:11 UTC
Labels: bug
