### ISSUE TITLE
`default` current case is empty after running ES

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#5586] opened 2023-06-16 10:19 UTC
**Describe the bug**
After a run of ES (I tried drogon) we end up with 3 cases; `default`, `default_prior` and `default_smoother_update`.
`default` is empty.

**To reproduce**
Steps to reproduce the behaviour:
1. source bleeding
2. run ES on drogon_ahm.ert

**Expected behaviour**
Only two cases, one with the prior and one with the posterior.
Consider https://github.com/equinor/ert/issues/4160 as well

**Comment by pinkwah** [comment] 2023-06-19 07:36
I think this is intended behaviour. ERT 5 creates an empty `default` case to mimic behaviour from ERT <5.

I agree it's stupid and we shouldn't have it, but I think that is an issue for another milestone.

**Comment by oyvindeide** [comment] 2023-06-20 07:10
Will close this now then, we all agree we should review this behavior, but for now the old behavior is ok.

**Closed by oyvindeide** 2023-06-20 07:10 UTC
Labels: bug
