### ISSUE TITLE
Ensemble naming with ES-MDA

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#7351] opened 2024-03-04 14:18 UTC
It's currently not possible to name the ensemble when running ES-MDA. It uses `default_<ITER>` when there aren't any ensembles, and (presumably) `f"{current_case_name}_<ITER>"` when it exists, regardless if it makes sense. This can be reproduced as follows:

1. Create a new Experiment and Ensemble via Manage Cases. Name the Ensemble "Foobar".
2. Start new ES_MDA run. Notice that it's not possible to change name of the Ensembles.
3. Open Manage Cases.
4. Observe that under ES_MDA run, every ensemble is named "Foobar_0".."Foobar_3", which was the name we gave to an unrelated run.

Instead, I think a simple fix is to always use `iter-<ITER>` as ensemble name when running with ES-MDA.

**Comment by oyvindeide** [comment] 2024-03-11 11:33
I was not able to reproduce this, I got the name from ES-MDA and not `foobar_`.

**Comment by oyvindeide** [comment] 2024-03-21 08:13
Not able to reprodue this, so closing this issue.

**Closed by oyvindeide** 2024-03-21 08:13 UTC
Labels: bug
