### ISSUE TITLE
GEN_DATA: REPORT_STEPS

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#4072] opened 2022-10-14 11:03 UTC
from the docs -
  > the report step(s) where you expect the forward model to create a result file. I.e. if the forward model should create a result file for report steps 50 and 100 this setting should be: REPORT_STEPS:50,100. If you have observations of this GEN_DATA data the RESTART setting of the corresponding GENERAL_OBSERVATION must match one of the values given by REPORT_STEPS

**Comment by oyvindeide** [comment] 2022-10-25 13:26
Not quite sure I understand what the issue is here, could you add some more context?

**Comment by valentin-krasontovitsch** [comment] 2022-10-25 19:36
the context is found in the meta issue - this is just a placeholder or reminder for the current config project. sorry, assigning a squad now.
we're noting things that should be considered during upcoming config validation work.

**Comment by oysteoh** [comment] 2022-11-08 12:42
If this is needed it needs more explaination and put into our todo column. If there is not much to add to this yet it should be closed. If needed there will be made an issue at a later point

**Comment by valentin-krasontovitsch** [comment] 2022-11-08 13:31
the idea of this issue was to remember to consider this in our validation work, instead of having a TODO comment, as we discussed.

the point is to not forget.

the context can be formulated generically, as we should make sure to validate this particular bit of logic in the config, we should do it as early as possible, and handle it in a meaningful way, communicating appropriately with the user.

I'll leave it at your discretion to decide whether this should remain open, or be closed.

**Comment by oysteoh** [comment] 2022-11-11 09:11
Closing this as not actionable. I would consider validation work an important part of the new parser and will not be forgotten. I cannot see this issue gives much value to have around. Please correct me if i'm wrong and we can reopen. If that is the case i want a new title on the issue and i guess then it should be a way to formalize a number of rules we really need to remember when validating which now will be lost / forgotten due to cleanup of old code.

**Closed by oysteoh** 2022-11-11 09:11 UTC
