### ISSUE TITLE
Fix integration tests on PBS cluster

### ISSUE THREAD

**Issue by xjules** [equinor/ert#7716] opened 2024-04-22 06:37 UTC
The following tests are sometimes timing out  when running on real cluster. 
```sh
self = <selectors.EpollSelector object at 0x7fdea8bbcc10>, timeout = -1

    def select(self, timeout=None):
        if timeout is None:
            timeout = -1
        elif timeout <= 0:
            timeout = 0
        else:
            # epoll_wait() has a resolution of 1 millisecond, round away
            # from zero to wait *at least* timeout seconds.
            timeout = math.ceil(timeout * 1e3) * 1e-3
    
        # epoll_wait() expects `maxevents` to be greater than zero;
        # we want to make sure that `select()` can be called when no
        # FD is registered.
        max_ev = max(len(self._fd_to_key), 1)
    
        ready = []
        try:
>           fd_event_list = self._selector.poll(timeout, max_ev)
E           Failed: Timeout >360.0s

/usr/lib64/python3.8/selectors.py:468: Failed
=========================== short test summary info ============================
FAILED integration_tests/scheduler/test_generic_driver.py::test_submit[OpenPBSDriver] - Failed: Timeout >360.0s
FAILED integration_tests/scheduler/test_generic_driver.py::test_submit_something_that_fails[OpenPBSDriver] - Failed: Timeout >360.0s
FAILED integration_tests/scheduler/test_generic_driver.py::test_kill[OpenPBSDriver] - Failed: Timeout >360.0s
```
https://github.com/equinor/komodo-releases/actions/runs/8755056479/job/24055175088
https://github.com/equinor/komodo-releases/actions/runs/8755056479/job/24055168487

**Potential solution:**
Catch timeout exceptions and run against mocked driver afterwards.

**Comment by berland** [comment] 2024-04-22 07:05
When we get here, we have already run the same tests with mocked drivers.

**Comment by xjules** [comment] 2024-04-22 10:20
In case we get timeout error, we should change the queue and rerun those tests.

**Comment by berland** [comment] 2024-04-23 11:38
Refactor this PR based on https://github.com/equinor/komodo-releases/pull/5646

**Comment by berland** [comment] 2024-04-29 14:02
New issue to take over: https://github.com/equinor/komodo-releases/issues/5692

**Comment by berland** [comment] 2024-05-03 08:39
Closing as wont-fix. The problem is not large enough to warrant the complexity a workaround will incur.

**Closed by berland** 2024-05-03 08:39 UTC
Labels: bug, flaky-test, scheduler
