### ISSUE TITLE
Switching case takes long time, and times out

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#3292] opened 2022-04-22 12:47 UTC
When using data in /project/oomph/scout/poly_large_synth, it takes a long time to switch cases. We also see a warning about opening an already opened fs.

~Sometimes (usually on switching the third time between large cases), the initial request times out.~  <- Fixed with setting a higher timeout value

We need to investigate what is occurring.

**Comment by oysteoh** [comment] 2022-05-03 08:22
Is there any actions for this issue? I guess at some point we tracked this down to be due to the fact ERT is changing file-system when switching case? And that there is some caching if already loaded? If the performance switching cases is the same across the native implementation of the plotter and the new using the API i guess this issue is not in the scope of our milestone?

**Comment by mortalisk** [comment] 2022-05-03 11:45
I am a bit unsure. Me and @frode-aarstad just made this issue so as not to forget it while we were solving other things.

**Comment by DanSava** [comment] 2022-05-04 08:30
Is not #3343 a duplicate of this issue?

**Comment by oysteoh** [comment] 2022-05-24 08:36
Related to #2198 

Switching cases loads a lot of data and it seems the bottleneck is the actual speed of NFS. Hence - closing this issue for now.

**Closed by oysteoh** 2022-05-24 08:36 UTC
Labels: enhancement, needs-discussion, visualization
