### ISSUE TITLE
GUI tests fail locally due to order dependency

### ISSUE THREAD

**Issue by berland** [equinor/ert#3725] opened 2022-08-09 11:12 UTC
**Describe the bug**
``` 
(3.8.b) [havb@be-lx895926:/work/projects/ert/tests/ert_tests/gui] stop-underlying-leak-fixing-3613$ pytest test_gui_load.py -x  # fails
==================================================== test session starts ====================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
PyQt5 5.15.7 -- Qt runtime 5.15.2 -- Qt compiled 5.15.2
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /work/projects/ert, configfile: pyproject.toml
plugins: anyio-3.6.1, ert-storage-0.3.15, dash-2.6.1, timeout-2.1.0, snapshot-0.9.0, raises-0.11, qt-4.1.0, mock-3.8.2, cov-3.0.0, benchmark-3.4.1, asyncio-0.19.0
asyncio: mode=auto
collected 4 items                                                                                                           

test_gui_load.py ..F

========================================================= FAILURES ==========================================================
_____________________________________________________ test_gui_iter_num _____________________________________________________
CALL ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/work/projects/ert/tests/ert_tests/gui/test_gui_load.py", line 141, in _assert_iter_in_args
    assert panel.getSimulationArguments().iter_num == 10
AttributeError: 'Arguments' object has no attribute 'iter_num'
________________________________________________________________________________
--------------------------------------------------- Captured stderr call ----------------------------------------------------
Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/work/projects/ert/tests/ert_tests/gui/test_gui_load.py", line 141, in _assert_iter_in_args
    assert panel.getSimulationArguments().iter_num == 10
AttributeError: 'Arguments' object has no attribute 'iter_num'
________________________________________________________________________________
================================================== short test summary info ==================================================
FAILED test_gui_load.py::test_gui_iter_num
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================ 1 failed, 2 passed in 1.73s ================================================
                                                                                                                                            
```

**To reproduce**
```
cd tests/ert_tests/gui
pytest test_gui_load.py::test_gui_iter_num  # succeeds
pytest test_gui_load.py -x  # fails
pytest test_gui_load.py::test_gui_iter_num test_gui_load.py::test_gui_full  # succeeds
pytest test_gui_load.py::test_gui_full test_gui_load.py::test_gui_iter_num  # fails
```

**Expected behaviour**
No dependency on order

**Environment**
 - OS:  RHEL7
 - ERT/Komodo release: bleeding
 - Python version: 3.8
 - Remote/HPC execution involved:no

**Comment by andreas-el** [comment] 2023-03-09 07:45
Not reproducible on bleeding 2023.03.09.
Closing issue as unable to reproduce.
All combinations provided were successful.

```
(testenv) andrli@be-lx919901 ~/project/ert/tests/unit_tests/gui (main)$ pytest test_gui_load.py::test_gui_iter_num 
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.8.14, pytest-7.2.0, pluggy-1.0.0
PyQt5 5.15.7 -- Qt runtime 5.15.2 -- Qt compiled 5.15.2
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /private/andrli/project/ert, configfile: pyproject.toml
plugins: timeout-2.1.0, qt-4.2.0, asyncio-0.20.2, snapshot-0.9.0, xdist-3.2.0, hypothesis-6.54.6, ert-storage-0.3.17, mock-3.10.0, anyio-3.6.1, raises-0.11, benchmark-3.4.1, dash-2.8.1, cov-3.0.0
asyncio: mode=auto
collected 1 item                                                                                                                                                                             

test_gui_load.py .                                                                                                                                                                     [100%]

===================================================================================== 1 passed in 13.62s =====================================================================================
(testenv) andrli@be-lx919901 ~/project/ert/tests/unit_tests/gui (main)$ pytest test_gui_load.py::test_gui_iter_num test_gui_load.py::test_gui_full
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.8.14, pytest-7.2.0, pluggy-1.0.0
PyQt5 5.15.7 -- Qt runtime 5.15.2 -- Qt compiled 5.15.2
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /private/andrli/project/ert, configfile: pyproject.toml
plugins: timeout-2.1.0, qt-4.2.0, asyncio-0.20.2, snapshot-0.9.0, xdist-3.2.0, hypothesis-6.54.6, ert-storage-0.3.17, mock-3.10.0, anyio-3.6.1, raises-0.11, benchmark-3.4.1, dash-2.8.1, cov-3.0.0
asyncio: mode=auto
collected 2 items                                                                                                                                                                            

test_gui_load.py ..                                                                                                                                                                    [100%]

================================================================================ 2 passed in 73.81s (0:01:13) ================================================================================
(testenv) andrli@be-lx919901 ~/project/ert/tests/unit_tests/gui (main)$ pytest test_gui_load.py::test_gui_full test_gui_load.py::test_gui_iter_num
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.8.14, pytest-7.2.0, pluggy-1.0.0
PyQt5 5.15.7 -- Qt runtime 5.15.2 -- Qt compiled 5.15.2
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /private/andrli/project/ert, configfile: pyproject.toml
plugins: timeout-2.1.0, qt-4.2.0, asyncio-0.20.2, snapshot-0.9.0, xdist-3.2.0, hypothesis-6.54.6, ert-storage-0.3.17, mock-3.10.0, anyio-3.6.1, raises-0.11, benchmark-3.4.1, dash-2.8.1, cov-3.0.0
asyncio: mode=auto
collected 2 items                                                                                                                                                                            

test_gui_load.py ..                                                                                                                                                                    [100%]

===================================================================================== 2 passed in 25.33s =====================================================================================
(testenv) andrli@be-lx919901 ~/project/ert/tests/unit_tests/gui (main)$ pytest test_gui_load.py -x 
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.8.14, pytest-7.2.0, pluggy-1.0.0
PyQt5 5.15.7 -- Qt runtime 5.15.2 -- Qt compiled 5.15.2
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /private/andrli/project/ert, configfile: pyproject.toml
plugins: timeout-2.1.0, qt-4.2.0, asyncio-0.20.2, snapshot-0.9.0, xdist-3.2.0, hypothesis-6.54.6, ert-storage-0.3.17, mock-3.10.0, anyio-3.6.1, raises-0.11, benchmark-3.4.1, dash-2.8.1, cov-3.0.0
asyncio: mode=auto
collected 12 items                                                                                                                                                                           

test_gui_load.py ............                                                                                                                                                          [100%]

====================================================================================== warnings summary ======================================================================================
tests/unit_tests/gui/test_gui_load.py::test_that_run_dialog_can_be_closed_after_used_to_open_plots
tests/unit_tests/gui/test_gui_load.py::test_that_run_dialog_can_be_closed_after_used_to_open_plots
tests/unit_tests/gui/test_gui_load.py::test_that_run_dialog_can_be_closed_after_used_to_open_plots
tests/unit_tests/gui/test_gui_load.py::test_that_run_dialog_can_be_closed_after_used_to_open_plots
tests/unit_tests/gui/test_gui_load.py::test_that_run_dialog_can_be_closed_after_used_to_open_plots
tests/unit_tests/gui/test_gui_load.py::test_that_run_dialog_can_be_closed_after_used_to_open_plots
  /private/andrli/project/ert/src/ert/gui/tools/plot/plot_widget.py:44: PendingDeprecationWarning: The set_tight_layout function will be deprecated in a future version. Use set_layout_engine instead.
    self._figure.set_tight_layout(True)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================================= 12 passed, 6 warnings in 93.17s (0:01:33) ==========================================================================
(testenv) andrli@be-lx919901 ~/project/ert/tests/unit_tests/gui (main)$ 
```

**Closed** 2023-03-09 07:45 UTC
Labels: bug
