### ISSUE TITLE
Summarize multiple GEN_OBS observation deactivations for readability

### ISSUE THREAD

**Issue by kwinkunks** [equinor/ert#7038] opened 2024-01-29 13:58 UTC
**Is your feature request related to a problem? Please describe.**
User Oddvar Lia [mentions in Slack](https://equinor.slack.com/archives/CDPJULWR4/p1706535251296469) that it is hard to interpret the reporting of deactivated observations:

> A question related to the report of decativation of observations in event viewer:
The table below is from a DROGON run (iteration = 0). There are 9 repeated warnings related to deactivating AMP_2020_2018_BASE for example. Does it mean that 9 of all the field observations AMP_2020_2018_BASE are deactivated? If so, maybe the observation number also could be reported? (Or maybe just one line per observation field but with percentage of how large fraction of the number of observations belonging to the observation field is actually deactivated (in this case 100% * 9/N where N is number of observations in the observation field AMP_2020_2018_BASE.)  Same comment can be said for other GEN_OBS having multiple obs like e.g TRACER_OBS in the same case as show below. 

![image](https://github.com/equinor/ert/assets/1692372/967267c6-1aa6-457d-a6d6-1adb6d2862f0)

**Describe the solution you'd like**
A summary would be helpful, eg

```
WARNING Deactivating 9 of 32 (28%) observations of AMP_2020_2018_BASE
WARNING Deactivating 9 of 32 (28%) observations of AMP_2020_2018_TOP
WARNING Deactivating 3 of 13 (23%) observations of TRACER_OBS
WARNING Deactivating observation: WGOR_A2_4
WARNING Deactivating observation: WGOR_A4_6
WARNING Deactivating observation: WWCT_A2_4
WARNING Deactivating observation: WWCT_A4_6
```

Have we thought about using colour and/or symbols as well?

**Describe alternatives you've considered**

**Additional context**
Possibly related, I'm not sure:

- https://github.com/equinor/ert/issues/6262 
- https://github.com/equinor/ert/issues/6954

**Comment by oyvindeide** [comment] 2024-01-30 13:01
Will close it as duplicate of #6262, and #6954 will also improve this.

**Closed by oyvindeide** 2024-01-30 13:01 UTC
Labels: enhancement
