### ISSUE TITLE
When workflow job fails the workflow as a whole still succeeds

### ISSUE THREAD

**Issue by joakim-hove** [equinor/ert#2955] opened 2022-02-21 19:20 UTC
**Describe the bug**
In the test: https://github.com/equinor/ert/blob/main/tests/libres_tests/res/enkf/test_row_scaling_case.py#L206 the only workflow job fails in current master[1], however the workflow as a whole is registered as passing and since the test itself does not really verify the results the test as a whole also succeeds - i.e. we have for some time had a false green test.

As I see it there are two problems here:

1. **Most importantly**: the workflow run code should correctly return `False` when one of the jobs has failed.
2. The test in question should be updated to actually verify the data in some way - then we would have detected this failure when it happened.

**Comment by BjarneHerland** [comment] 2022-05-24 11:38
@oyvindeide do you know if this is still an issue? I.e. does the abovementioned test still have the weakness described ?

**Comment by oyvindeide** [comment] 2022-05-24 12:31
Yes, this is still the case, but this is a duplicate of: https://github.com/equinor/ert/issues/2386

**Closed by oyvindeide** 2022-05-24 12:31 UTC
Labels: bug
