### ISSUE TITLE
Ert never completes even though all jobs are complete and results are loaded

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#4685] opened 2023-01-19 08:25 UTC
**Describe the bug**
Ert is stuck on `Running` in the detailed progress window. The attached image shows the detailed progress window for an ERT run. From the logs it is shown

> Simulation started:
> 2023-01-13 01:10:57,048 - ert.cli.model_factory - MainThread - INFO - Initiating experiment
>
>Information realization 0 (which is highlighted in the image)
>2023-01-13 01:11:37,716 - res.job_queue - Thread-5 - DEBUG - Set job_name-0(0) to JOB_QUEUE_RUNNING
>2023-01-13 02:35:13,786 - res.job_queue - Thread-5 - DEBUG - Set job_name-0(0) to JOB_QUEUE_DONE
>2023-01-13 02:35:13,798 - res.job_queue - Thread-5 - DEBUG - Set job_name-0(0) to JOB_QUEUE_SUCCESS
> 
> Last job:
> 2023-01-13 04:23:46,506 - res.job_queue - Thread-64 - DEBUG - Set job_name to JOB_QUEUE_SUCCESS
> 
> Completed:
> 2023-01-13 04:35:35,492 - ert.gui.simulation.tracker_worker - Dummy-2 - DEBUG - got end event
> 2023-01-13 08:23:37,702 - root - MainThread - DEBUG - Resetting environment variable ERT_SITE_CONFIG

```
# time elapsed gui:
>>> datetime.timedelta(hours=4,minutes=1,seconds=45)
datetime.timedelta(seconds=14505)

# time required for ert to complete:
>>> datetime.datetime(2023,1,13,4,35,35)-datetime.datetime(2023,1,13,1,10,57)
datetime.timedelta(seconds=12278)
```

**Notes that could be helpful**
The `got end event` is logged in `TrackerWorker` which calls the `SnapshotModel(QAbstractItemModel).renderer()` and thus renders the DetailedProgress window. Meaning the status of the experiment should have been progressed all the way to the GUI.

Hence the ensemble experiment should have been set to completed at the time of the screenshot

Note that the boarder on each realization is set based on information from `JobQueue` and is pushed to the `EvaluationServer` with `JobQueue._publish_changes` within the ert application itself, while the status on each job within the forward model is based on information from `JobRunner` running on the compute node.

The information from `JobQueue` has precedence over `JobRunner` and in the scenario of information not being received from `JobRunner` Ert will continue. The detailed progress window will then display yellow jobs, while the boarder will be marked green. This is not the case here.

**To reproduce**
Not consistently reproducible.

**Expected behaviour**
Expects the detailed progress window to update as jobs change status.

**Screenshots**
![ERT_1_1](https://user-images.githubusercontent.com/26920711/213387903-0fda68d4-7e14-4cd2-a69e-1e6f32461b3d.JPG)

**Environment**
 - OS: [e.g. RHEL7]
 - ERT/Komodo release: [e.g. 2.18 or 2020.12.00]
 - Python version
 - Remote/HPC execution involved: [yes|no]

**Additional context**

**Comment by eivindjahren** [comment] 2023-01-19 08:47
Have also observed the summary saying `PENDING (0/110)`, but the detailed view showing several jobs stuck pending.

**Comment by ErikHelland** [comment] 2023-01-19 11:12
I have also observed the same problem with jobs hanging at different timesteps - with status window not representing actual status (see image below). All steps stuck at pending and eclipse job in certain realizations stuck (was not a problem previously).
![image](https://user-images.githubusercontent.com/123075697/213427404-0880d52d-e642-47ab-9b9f-a3e134338b0f.png)

**Comment by sondreso** [comment] 2023-03-13 11:35
This issue has not been seen after the original report, and we are closing it since we are not able to reproduce it. This was happening at the same time as infrastructure upgrades where implemented, and probably caused some intermittent issues. Feel free to reopen if this happens again!

**Closed by sondreso** 2023-03-13 11:35 UTC
Labels: bug
