### ISSUE TITLE
Documentation - poor description of kw

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#891] opened 2020-05-12 09:49 UTC
Docs of kw ENKF_ALPHA refers to UPDATE_SETTINGS and OVERLAP_LIMIT, but neither of these are mentioned further in the docs. Suggestion is to write a proper description of ENKF_ALPHA, the assess what to do with the others.

**Comment by oysteoh** [comment] 2020-08-13 12:00
Duplicate of #958

**Comment by oysteoh** [comment] 2020-08-14 07:03
Related to #958

**Comment by oysteoh** [comment] 2020-08-14 07:05
Duplicate of #958

**Closed** 2020-08-17 18:04 UTC
Labels: documentation
