### ISSUE TITLE
failure in test_parameter_example

### ISSUE THREAD

**Issue by JHolba** [equinor/ert#7458] opened 2024-03-14 13:13 UTC
**Describe the bug**
Hypothesis test triggered two different exceptions in test_parameter_example. Second error seems to be related to #7453.

The first error looks like it might be due to the min value of FieldParameter being excessively large. There are warnings from numpy about overflows and invalid values during the run.
error at: https://github.com/equinor/ert/actions/runs/8278986970/job/22652560955?pr=7452#step:8:3875
see min value at: https://github.com/equinor/ert/actions/runs/8278986970/job/22652560955?pr=7452#step:8:3908

Possible fix may be to limit the min value in hypothesis.
We should maybe consider catching the nan/inf problem earlier and giving the user better feedback.

**To reproduce**
reproduction instructions at: https://github.com/equinor/ert/actions/runs/8278986970/job/22652560955?pr=7452#step:8:3951

**Expected behaviour**
Test passes

**Environment**
 - linux github runner
 - Python version 3.11
 - Remote/HPC execution involved: no

**Comment by sondreso** [comment] 2024-03-18 08:17
Duplicate of https://github.com/equinor/ert/issues/7412

**Closed by sondreso** 2024-03-18 08:17 UTC
Labels: bug
