### ISSUE TITLE
Create minimal RMS test case and automatically run it for each <thing>

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#642] opened 2020-01-14 10:30 UTC
The minimal RMS test case should test a RMS happy path, whatever that is. It could draw inspiration from the ert_spe1 case we already run (defined in the team repo).

<thing> is most likely a new komodo release.

**Comment by markusdregi** [comment] 2020-01-24 09:17
We should talk to Jan Rivenæs about this.

**Comment by oysteoh** [comment] 2020-02-03 14:08
current status - wait for @berland and @jcrivenaes to create tar's with RMS cases which we can use to run tests against RMS.

**Comment by sondreso** [comment] 2020-08-19 12:11
Is there any updates on this issue?

**Comment by oysteoh** [comment] 2020-08-19 13:36
@jcrivenaes says "We have been working ( and still is ) with a new and better syntetic model called Dragon ( which will replace Reek ). This would be ideal as a minimal RMS test case as it contains much python with integration towards xtgeo, fmu-tools etc"

**Comment by markusdregi** [comment] 2021-04-20 05:20
Duplicate of https://github.com/equinor/fmu-dev/issues/8

**Closed by markusdregi** 2021-04-20 05:20 UTC
Labels: automation, blocked, testing
