### ISSUE TITLE
Event Viewer gives confusing deprecations warning about integers being required

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#4766] opened 2023-02-01 08:38 UTC
**Describe the bug**
When running drogon with the event viewer open, it gives a lot of deprecation warnings:
```
WARNING  /prog/res/komodo/2022.12.03-py38-rhel7/root/lib64/python3.8/site-packages/ert/_c_wrappers/job_queue/forward_model.py:119: DeprecationWarning: an integer is required (got type ContentTypeEnum).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  "arg_types": [job_kw.kw_from_type(typ) for typ in job.arg_types],
```

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui drogon_ahm.ert`
3. Press event viewer button
4. Run experiment (test-run)
5. Observe event viewer

**Expected behaviour**
Comprehensible events in the veiwer. If there is a user caused error this should be clearly indicated.

**Screenshots**
![Screenshot from 2023-02-01 09-31-53](https://user-images.githubusercontent.com/596662/215992165-08883ad5-286b-4759-89df-6264cb9effe0.png)

**Environment**
 - OS:  RHEL7
 - ERT/Komodo release: 2022.12.03
 - Python version 3.8
 - Remote/HPC execution involved: no

**Comment by berland** [comment] 2023-02-06 07:28
Duplicate of #4687

**Closed by berland** 2023-02-06 07:28 UTC
Labels: bug
