### ISSUE TITLE
Style checking/linting

### ISSUE THREAD

**Issue by verveerpj** [equinor/ert#1347] opened 2021-01-29 10:23 UTC
**Is your feature request related to a problem? Please describe.**
I noticed the ert code base does not use a linter.

**Describe the solution you'd like**
Use a linter that checks pep8 compliance, and our own style preferences.

**Describe alternatives you've considered**
`pylint` or `flake8`

**Additional context**
The linter should probably  only be used on the new modules that are being introduced.

**Comment by markusdregi** [comment] 2021-01-29 10:31
Related to: https://github.com/equinor/ert/issues/1346

**Comment by markusdregi** [comment] 2021-01-29 10:32
Note that we already run `flake8` and would like to run `pylint` as well on the `ert3` modules.

**Comment by markusdregi** [comment] 2021-03-10 19:40
Duplicate of #1346

**Closed by markusdregi** 2021-03-10 19:40 UTC
Labels: enhancement, good first issue
