### ISSUE TITLE
Loading indicator when manual analysis is performed

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#4146] opened 2022-10-27 13:11 UTC
When using RunAnalysis the `Run` button should be greyed out and there should be a spinning wheel or similar to indicate that the analysis is running.

**Comment by oyvindeide** [comment] 2023-01-27 15:08
This might be solved already, should check that first.

**Comment by oyvindeide** [comment] 2023-01-27 15:08
Related to #4094

**Comment by sondreso** [comment] 2023-03-24 14:46
Duplicate of https://github.com/equinor/ert/issues/4840

**Closed by sondreso** 2023-03-24 14:46 UTC
Labels: user request, good first issue
