### ISSUE TITLE
Storage: Add '--test-fixture' option for integration-testing webviz-ert

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#1389] opened 2021-02-10 23:07 UTC
Add an option called `--test-fixture=` to `ert api` which will load a pre-made database from a YAML file. I take inspiration from Ruby on Rails' text fixture system:

```yaml
ensemble:
  - id: default
    name: default
    num_realizations: 2

response_definition:
  - id: poly_res
    ensemble_id: default
    name: POLY_RES

response:
  - values: [1.0, 2.0, 3.0]
    indices: [1, 2, 3]

observation:
  - id: poly_obs
    name: POLY_OBS
    values: [1.0, 4.0, 9.0]
    errors: [0.1, 0.2, 0.3]

observation_response_definition_link:
  - observation_id: poly_obs
    response_definition_id: poly_res
```

In order to make our lives more magical, I make the following assumptions:
1. We're bypassing SqlAlchemy entirely and creating an SQL transaction from scratch
2. The outermost keys are equivalent to some SQL table name (ie, `ensemble` is a table that exists)
3. Each key is a list
4. Each element of this list is an object where each key corresponds to a _real_ column (ie, not a `sqlalchemy.relationship`)
5. The `id` column is special, in that if it's a `str`, then it's replaced with a unique `int` and placed in a mapping of names to `id`s
6. Any column that ends with `_id` is also special, in that if it's a `str`, it get replaced with the `int` from the aforementioned mapping

**Comment by dotfloat** [comment] 2021-04-13 09:12
I still like the idea of this but I decided not to proceed just yet. We should wait until there's a substantial amount of test data that is difficult to deal with, rather than guessing what the future might look like now.

**Comment by markusdregi** [comment] 2021-04-26 13:50
@dotfloat: is this not a duplicate of https://github.com/equinor/ert-storage/issues/55

**Comment by dotfloat** [comment] 2021-04-26 14:07
It is not. It is a mechanism for users (`ert`, `webviz-ert`) to create their own datasets in a readable way. After picking it up, I think we will end up closing as WONTFIX as it is doubtful that this is possible to generalise in a way that will not break on every minor version bump.

**Comment by markusdregi** [comment] 2021-04-27 11:07
I see 👍🏻

**Closed** 2024-02-26 20:09 UTC
Labels: storage
