### ISSUE TITLE
Handle timeout in storage properly

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#2751] opened 2022-01-20 14:55 UTC
In the scenario of large files as records in storage, the default timeout of 5 seconds is not enough. In https://github.com/equinor/ert/pull/2729 this was increased to the magical number of 60. However handling timeout should be addressed in a better manner.

**Comment by lars-petter-hauge** [comment] 2022-01-25 11:01
The current implementation is very rough, simply passing the same timeout to any type of connection issues to the requests. It is possible to have granular control, specifying timeout for connection, read, write etc independently [Fine tune configuration](https://www.python-httpx.org/advanced/#fine-tuning-the-configuration)

We can set this at a much higher level as well, on the `client` initialisation for instance

**Comment by oyvindeide** [comment] 2024-08-05 13:30
Think this was related to ert3? If so, will close, if it is related to plotting, it is a duplicate of: https://github.com/equinor/ert/issues/5065

**Closed by oyvindeide** 2024-08-05 13:30 UTC
