### ISSUE TITLE
Warnings during plotting 

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#533] opened 2019-10-29 15:11 UTC
While plotting I get warnings:
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"

These should be addressed before new release.

**Comment by dotfloat** [comment] 2019-10-30 09:29
I'm familiar with the warnings in other software, but I'm not able to reproduce this for `ert`. I tried it on my local Red Hat 7.7 desktop and an RGS node.

How are you running `ert`?

Do note that both of these warnings can be ignored safely. The modules aren't required:
`canberra-gtk-module` is used for playing sounds; `pk-gtk-module` is used for managing system packages.

**Comment by eivindsm** [comment] 2019-10-30 10:21
Hi,
I was testing ERT on the RGS nodes that are running RHEEL6. Log on through: https://rgs.statoil.no/main.cgi , to experience ERT the way our users are.

**Comment by dotfloat** [comment] 2019-10-30 12:01
Yup. I'm using the HP RG client software to connect to an RGS node graphically. I've tried both bleeding and unstable `ert` builds from komodo, on both Bergen and Trondheim RGS. I'm testing with the following:

- Enter the `test-data/local/poly_example` directory from this repository.
- `ert gui poly.ert`
- ERT shows up, I run a single realisation, then click "Create Plot".

No warnings occur in terminal.

The module files exist on the nodes:
```
[zom@be-linrgsn206 ~]$ ls /usr/lib64/gtk-2.0/modules/
libatk-bridge.so           libferret.so      libgail.so
libcanberra-gtk-module.so  libgail-gnome.so  libpk-gtk-module.so
^~~~~~~~~~~~~~~~~~~~~~~~~                    ^~~~~~~~~~~~~~~~~~~
```

**Comment by dotfloat** [comment] 2019-11-04 13:17
I'm closing this issue because fixing it is far beyond the scope of this project. The warnings can be safely ignored and can only be fixed finding what's causing the warnings in your personal configuration or in the system's configurations.

**Closed by dotfloat** 2019-11-04 13:17 UTC
