### ISSUE TITLE
Running ert with >= 200 realizations fails

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#5273] opened 2023-04-25 06:25 UTC
**Describe the bug**
A [user has reported](https://equinor.slack.com/archives/CDPJULWR4/p1681802851507989) [INTERNAL LINK] that ert fails in the start of iter-1. Iter-0 completes successfully, and the analysis step seems to run fine. The ensemble setup ran fine with 50 realizations, but 200 did not work, nor did 100. At first it was suspected that they ran out of memory, but that seems not to be the case.

Fails here: https://github.com/equinor/ert/blob/e21998046cc85d6dfbcc4eb0c3fa5c370b151a71/src/ert/_c_wrappers/job_queue/queue.py#L471

**Environment**
Note! Using komodo 2022.11.02, but the queue interaction should not be that different from `main`.

**Comment by valentin-krasontovitsch** [comment] 2023-05-02 16:58
### local trial - summary

after some advice from Øyvind i found the poly template and used a script to generate lots of data, and ran esmda locally on my machine. no problem, went from itereation 0 to iteration 3.

### local trial - details

on ert main prepare a big case
```
cd tests/performance_tests
python3 performance_utils.py
```

copy case over to local ert checkout, to have control over files and add to git
we assume to be in ert dir
```
cp /tmp/[TEMP_DIR]/poly test-data/big-poly-case
```

all config modifications are done in poly.ert, see branch for details
- added dummy file with silly text content
- added a bunch of forward models copying the file to new filename
- remove the max running queue option
- run esmda, on local machine, with local queue

**Comment by valentin-krasontovitsch** [comment] 2023-05-02 17:08
### rgs node trial - details

checked out above setup, changed queue system to `LSF`, and started by running

```
ert es_mda --realizations 0-199 --target-case default_%d --weights '4,2,1' poly.ert
```

(i prefer putty over the gui)

**Comment by hnformentin** [comment] 2023-05-09 12:35
this could be connected to https://github.com/equinor/ert/issues/4708

**Comment by valentin-krasontovitsch** [comment] 2023-05-11 07:38
branch on my fork for reproducing the issue: https://github.com/valentin-krasontovitsch/ert/tree/test-200-realizations
ping me here or on slack in case you wonder if the latest changes have been pushed!

**Comment by valentin-krasontovitsch** [comment] 2023-05-23 11:37
so after realizing that the local reproduction was due to moving the laptop and changing the wifi controller's ip address, we were kind of back to square one, but learned a lot about the websocket communication in ert.

now we are trying to

- reproduce the initial user's reported case
- reproduce using the drogon, with an increased number of realizations (300)
- check out another user report made on [yammer](https://web.yammer.com/main/org/statoil.com/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMjI2OTEzMTA5OTkzODgxNiJ9) [INTERNAL LINK]

### drogon setup

we [copied the latest release of drogon](https://fmu-docs.equinor.com/docs/fmu-coursedocs/fmu-general/00_general-info/download-tutorial-project.html) [INTERNAL LINK], grabbing the tar archive from the repo and unpacking it locally on an rgs node. 

we're gonna run the `drogon_ahm.ert` config file, using the ESMDA algorithm.

to increase the number of realizations, we had to 

- specify the number `NUM_REALIZATIONS 300` in the config file
- modify the design matrix, which is located in `../input/distributions/design_matrix_ahm.xlsx`, adding ca. 200 more rows by
  * increasing the left most column (realization number) by one in each row
  * copy the next two columns (`SENSNAME`, `SENSCASE`) exactly (constant value in each row)
  * copying the rightmost columns after the RMS SEED as a block and pasting it twice, and
  * increase the RMS SEED by one in each ROW (continuing the existing pattern), BUT skip number 1112 (it caused RMS to fail, only GOD aka haavard knows why) - i continued with 1124 after 1111 

finally just run (for command line execution):

```
ert es_mda --realizations 0-299 --target-case default_%d --weights '4,2,1' drogon_ahm.ert
```

or start the gui and do the thing (esmda default options) there.

### observations of symptoms

**Comment by valentin-krasontovitsch** [comment] 2023-06-06 10:53
## reproducing the case originally reported

### get the model
create a personal dir (no data should leave the assets environment):

```
mkdir /project/johan_sverdrup/resmod/ff/users/[YOUR_USERNAME]
```

the latest model can be found in

```
/project/johan_sverdrup/resmod/ff/users/tomal/23.0.1_16022023_surface2_poly_newrms
```
copy the whole thing over, and you may find the ert config file we've been using in (relative paths now)
```
ert/model/newrms_23p0p1_history.ert
```

the scratch path will be `/scratch/johan_sverdrup/[YOUR_USERNAME]`, so no need to modify anything there.
start it with `ert gui newrms_23p0p1_history.ert`, and run two pre simulation workflows:

- 



it will create

**Comment by valentin-krasontovitsch** [comment] 2023-06-07 07:16
ran said model with [a branch](https://github.com/valentin-krasontovitsch/ert/tree/test-200-realizations) based on somewhat current main, with several fixes included (timeouts increased to 60 seconds, job queue is reusing websockets connection instead of creating new connection every time it publishes (possibly empty list of) changes), starting may 31st.

log files are in `/project/johan_sverdrup/resmod/ff/users/vkra/23.0.1_16022023_surface2_poly_newrms/ert/model/logs` with timestamp `2023-05-31T1427`
scratch has been moved to `/scratch/johan_sverdrup/vkra/23p0p1_new_rms_test_2023-05-31`

we have the following situation:

### ert-log
- no particular exceptions
- some job queue connection trial timeouts, but finally manages to connect as we have another log "we are in _publish_changes"

**Comment by valentin-krasontovitsch** [comment] 2023-06-12 11:43
another thread / idea to follow is that one user is running a setup with 300 realizations successfully, using komodo 2022.11.rc7. could check the diff between that version and ... well, actually, 2022.11 (stable, whichever patch release that was), already failed as per initial report...

**Comment by kvashchuka** [comment] 2023-06-12 12:59
comparison between ert versions in mentioned komodo releases
https://github.com/equinor/ert/compare/4.1.0-rc3...4.1.4

**Comment by xjules** [comment] 2023-06-14 11:14
NB: When the jobs are only pending we need to ssh into the compute cluster first, which in a default case in Stavanger would be: `/usr/bin/ssh st-grid03.st.statoil.no`

**Comment by xjules** [comment] 2023-06-14 14:24
Updating the issue with the note from @valentin-krasontovitsch about when we got the heavy event processing:
```
2023-06-01 20:36:36,539 - ert.ensemble_evaluator.dispatch - processed 31 events in 4.172715s. 88 left in queue
2023-06-01 20:37:04,060 - ert.ensemble_evaluator.dispatch - processed 168 events in 25.486581s. 199 left in queue
2023-06-01 20:40:14,327 - ert.ensemble_evaluator.dispatch - processed 199 events in 148.126047s. 9526 left in queue
2023-06-01 20:47:51,125 - ert.ensemble_evaluator.dispatch - processed 1000 events in 446.345663s. 30881 left in queue
2023-06-01 20:49:33,615 - ert.ensemble_evaluator.dispatch - processed 1000 events in 28.171717s. 38835 left in queue
2023-06-01 20:55:31,811 - ert.ensemble_evaluator.dispatch - processed 1000 events in 210.772313s. 58862 left in queue
2023-06-01 20:58:12,007 - ert.ensemble_evaluator.dispatch - processed 1000 events in 149.863073s. 57862 left in queue
```

**Comment by berland** [comment] 2023-06-15 13:10
This problem can be reproduced on the poly_example with something along the following:

`QUEUE_OPTION LOCAL MAX_RUNNING 500`
`NUM_REALIZATIONS 500`

and repeat `SIMULATION_JOB poly_eval` maybe 50-100 times.

in `poly_eval.py` add
`import time`
and 
`time.sleep(1)` at the end of `main`.

**Comment by xjules** [comment] 2023-06-16 08:43
When reproducing the poly_example with `valentin/test-threading-sleep-with-poly` branch It seems that all went well 👍 
No timeout errors.

![Image](https://github.com/equinor/ert/assets/6409506/01692a47-4a29-48fa-8f72-60978f329725)

Nevertheless, the GUI was extremely not responsive during the actual run. We might need to look at that.

**Comment by valentin-krasontovitsch** [comment] 2023-06-23 08:46
sadly the fixes were not enough, reopening

**Comment by valentin-krasontovitsch** [comment] 2023-06-23 13:07
latest test run of user model with "fixes" of

- introducing sleep in job runner in an attempt to reduce number of events
- letting the gui reconnect indefinitely instead of taking it down

finished iter-0, and then the gui was basically hanging.
while the server was unresponsive, because very busy dealing with messages from other clients, the gui was trying to reconnect. previously, it failed after three unsuccessful attempts.
the "fix" we implemented yesterday was to not let the gui fail, but let it retry indefinitely. the result is that it does not fail (yeahy), but while it's not connected, it also doesn't receive the messages it should get from the server (status updates about forward models and realizations) - once it reconnects, it waits for messages, but everything is finished (which it doesn't know), and it stays spinning, waiting for updates that never come.
that is at least my current understanding.

several ideas:
- somehow make sure that the server waits for the gui to be connected when it tries to publish changes (at the moment, it sends out changes to all connected clients, which can be none)
- don't drop the connection when the server gets busy, remove the "ping-pong" mechanism that detects a bad connection and times out currently (might have unintended side effects when the connection is bad for other reasons)
- investigate what the frick is creating so many messages, and / or why it's taking so long to process them

**Comment by valentin-krasontovitsch** [comment] 2023-06-23 18:06
exploring the idea of disabling the ping pong mechanism on the client side.

testing locally with a simple client and server script, we see that

- setting `ping_timeout` to `None` in the client's connect call stops the client from closing the connection on timed out pings (maybe because no pings are sent, i'm not sure)
- if the server shuts down, the client keeps trying to reconnect even though it's getting a `ConnectionRefused` error because nothing is listening on the port anymore. that's potentially bad news for us, as previous trials seemed to indicate that the client fails immediately if nothing is reachable under the given address. should explore undesirable states and figure out if it's a problem or not

**Comment by valentin-krasontovitsch** [comment] 2023-06-27 20:26
re: duct-tape.

we 
- reduced the batch-size of the batching dispatcher to 100 (avoid long events processing times)
- added a simple sleep of five seconds after every forward model status update in the job runner (relieve message pressure, slow things down at the source)
- increase sleep in job_queue from 1 to 30 seconds (relieve thread switching load)
- added five seconds sleep in evaluator tracker (slow down updates in the gui - not sure of the intention here anymore, now that i'm writing it, maybe also to relieve thread switching stress)

this lead to

- reduced events processing times: only 15 two-digit durations, between 10 and 20 seconds, and one 105 seconds duration
- after 1.5 hours, the first iteration of an esmda run of `big_poly_case` still had not finished, even though all realizations had finished
- according to the GUI, all realizations had state running
- at the time of sending ctrl-c, there were still over 20k events left for the ee server to process and propagate to the gui's tracker
- there was but one timeout in those 1.5 hours reported by the ee server
- no other errors were reported

overall, I think that our adjustment maybe was good - went in the right direction, this was after all the (hopefully) somewhat crazy artificial case with 200 realizations and 200 silly fast-running forward models - but perhaps too conservative.

gonna try a more dynamic approach next, we're we any time the events processing time goes >= 10 seconds, we reduce the batch size and increase the sleep (of the batching dispatcher), reverting if processing time goes down.

**Comment by valentin-krasontovitsch** [comment] 2023-06-27 21:16
[dynamic.diff.txt](https://github.com/equinor/ert/files/11887365/dynamic.diff.txt)

this seems to do some tricks - events are not lagging behind anymore, they're trickling in and getting processed in due time. no runreasonable processing times, a handful above 10 (top: 35).

yet it seems that execution of forward models is delayed on compute nodes.

perhaps the sleep in the job runner can be shortened or removed.

this feels like fiddling with something, and possibly making a brittle solution... user model tests will show more.

**Comment by valentin-krasontovitsch** [comment] 2023-07-03 11:55
to investigate the last question, i've

- removed the sleep in the job runner
- removed the sleep in the evaluator (gui)
- added some debug log about the job queue node status

and run the big poly case again.

this is all btw happening on the branch `detailed-study-many-realz` on my fork...

**Comment by valentin-krasontovitsch** [comment] 2023-07-15 20:57
so after a bit of work was done mostly by @berland, which as far as we could
tell massively sped up the processing that was being logged, and after fixing
all (that we found) remaining bugs the came with the rewrite of the (partial)
snapshot class, we had another very optimistic and hopeful test of the user
model.
we failed.
we saw timeouts again :sob:
and we saw durations of up to 900 seconds!

```
2023-07-15 15:55:48,417 processed 413 events in 130.765714s. 0 left in queue
2023-07-15 16:03:14,224 processed 1000 events in 317.391545s. 4517 left in queue
2023-07-15 16:07:55,578 processed 1000 events in 197.217101s. 12116 left in queue
2023-07-15 16:10:40,980 processed 1000 events in 110.467765s. 12591 left in queue
2023-07-15 16:18:08,543 processed 1000 events in 351.514885s. 11459 left in queue
2023-07-15 16:21:09,084 processed 1000 events in 112.926649s. 17759 left in queue
2023-07-15 16:26:57,042 processed 1000 events in 161.048984s. 14759 left in queue
2023-07-15 16:45:45,262 processed 1000 events in 914.408085s. 15263 left in queue
2023-07-15 17:05:02,859 processed 1000 events in 741.990857s. 37063 left in queue
2023-07-15 17:12:23,042 processed 1000 events in 149.200687s. 56336 left in queue
```

and finally the monitor brought down ert again

```
2023-07-15 16:01:04,460 - ert.ensemble_evaluator.evaluator - \
  ert_gui_simulation_thread - DEBUG - \
  run_and_get_successful_realizations caught Connection \
  timeout to host wss://10.217.147.132:51839/healthcheck.\
  3 unsuccessful attempts
2023-07-15 16:01:04,460 - ert.ensemble_evaluator.evaluator - \
  ert_gui_simulation_thread - DEBUG - Max connection attempts reached
2023-07-15 16:01:04,460 - ert.ensemble_evaluator.evaluator - \
  ert_gui_simulation_thread - DEBUG - Cancelling current ensemble
```

i'm kind of at end again, and confused - seems like we've come round again to
the original issue.

i'm confused, because I posted on slack that timings were awesome and whatnot -
BUT it may be that we did not get good enough of a test. in the case above, we
start failing around 16:01 - realization 22 (which always fails) failed at
14:56, ca. 1 hour earlier. if i remember correctly, in the previous case which
i thought was triumphant, the run failed because the failure of realization 22
was not handled correctly. this means that the times we saw there where before
the actual bad storm that apparently occurs later for this model...

so to ascertain my own sanity, i'm gonna run some basic tests. i'm still unsure
what is going on, and why we have these long processing times in the user model
when we have them. we have one storm first, starting at around 12:17, but
durations don't get up 2 seconds, with 40k max left in queue.
then you have the storm starting at around 16:03, with max 68k left in queue,
which takes down the app and durations of up to 900 seconds.
but at the same time you have outliers:

```
2023-07-15 15:29:13,617 processed 52 events in 69.471989s. 0 left in queue
2023-07-15 15:49:22,779 processed 138 events in 49.568064s. 0 left in queue
2023-07-15 15:50:32,318 processed 1000 events in 43.629527s. 606 left in queue
```

and these I cannot explain at all. This big variation in processing times, it
either means that

- we are processing some really complicated events, or have complicated state
  that we process the events in, which leads to long durations, or
- there is something else churning in other threads which steals resources from
  the thread responsible for processing events

we're gonna try to test the last assumption, and take as a culprit "the gui",
trying to run CLI and GUI and compare times.

## dummy case

we run the dummy example:

- config file `dummy.ert` given below
- local dev machine
- used `dummy-file` has content a few random string, like "hello world"

config file:
```
QUEUE_SYSTEM LOCAL
QUEUE_OPTION LOCAL MAX_RUNNING 300

RUNPATH output/realization-<IENS>/iter-<ITER>

NUM_REALIZATIONS 200
MIN_REALIZATIONS 1
MAX_SUBMIT 1

FORWARD_MODEL COPY_FILE(<FROM>=<CONFIG_PATH>/dummy-file,<TO>=<RUNPATH>/copy-of-dummy-file)
-- repeat above line ca. 228 times
```

### CLI

we run with the CLI, using `ert ensemble_experiment dummy.ert`

#### our branch

we run on branch `simple-snapshot-investigation-rebase` of my own fork, commit
`49ff6a1d`

this gives us ee logs where

- we have at most 60k events left in queue
- all processing durations are below 1 second

#### main

we run on `main`, which at the moment means commit `db9424ced0b`

this gives us ee logs where

- we have at most 106k events left in queue
- processing times are first bach 14 seconds, then stable at 2-4 seconds while
  the queue builds up, then between 0 and 2 seconds while the queue is worked
  off and there are no more messages coming in; last batch again takes 14
  seconds
- finishing takes a moment even after everything is seemingly done, not sure
  why

### GUI

we run with the gui, changing to ensemble experiment and hitting go immediately

#### main

we run on `main`, which at the moment means commit `db9424ced0b`

simlar to CLI run, except that during queue build-up, durations are slightly
longer, between 2 and 6 seconds - after that, they stabilize below one second!
total duration gui window 8 minutes, ert log file last timestamp minus first
timestamp confirms 8 minutes (and 13 seconds)

#### our branch
we run on branch `simple-snapshot-investigation-rebase` of my own fork, commit
`49ff6a1d`

- max 72k left in queue
- during buildup times of 0.3-0.8 seconds
- cool-down times of 0.07-0.13 seconds
- no extreme times for first or last batch

total duration gui - 5 minutes 48 seconds (so there's something we're doing
right), logs confirm (5 seconds more)

TODO we should try this on an RGS node, local queue might make things, i dunno,
too slow?!

**Comment by valentin-krasontovitsch** [comment] 2023-07-17 06:09
## dummy case on RGS-onprem

run as in comment above, except on an RGS node
we needed to change queue options in `dummy.ert` to
```
QUEUE_SYSTEM LSF
QUEUE_OPTION LSF MAX_RUNNING 300
```

BTW we always cleared storage and output before running again, but sometimes
kept logs around

### CLI

we run with the CLI, using `ert ensemble_experiment dummy.ert`

#### bleeding

we run with komodo bleeding (which was green, btw, awesome), which has ert main
at commit `5e3164269`.

this gives us ee logs where

```
2023-07-16 10:43:59,066 processed 1 events in 0.034413s. 0 left in queue
2023-07-16 10:44:41,281 processed 358 events in 14.002437s. 0 left in queue
2023-07-16 10:45:23,631 processed 99 events in 26.151736s. 0 left in queue
2023-07-16 10:45:59,836 processed 1000 events in 28.127329s. 44328 left in queue
2023-07-16 10:46:22,825 processed 1000 events in 20.342448s. 94801 left in queue
2023-07-16 10:46:25,912 processed 1000 events in 1.083446s. 134206 left in queue
2023-07-16 10:46:31,880 processed 1000 events in 3.955166s. 133212 left in queue
2023-07-16 10:46:37,741 processed 1000 events in 3.837912s. 132229 left in queue
```


- we have at most 134k events left in queue
- first couple batches: 14, 26, 28, 20 seconds
- then stabilizes between 3-5 seconds, with some singleton outliers
  (5,9,7,18,8,23 seconds)
- final batch took 79 seconds and caused cli monitor to disconnect
- the CLI monitor is way behind on info - when 200 realizations have had
  `JOB_QUEUE_SUCCESS`, it's still showing 75 waiting and 103 running, only 20
  finished. indeed, after 22 minutes, it says "Simulation completed", without
  making much progress on realization states...
- finally, after 36 minutes, also the CLI reported completion. indeed, the ert
  log file had a running duration (last timestamp - first timestamp) of 37
  minutes, likewise for ee file, although in the ee file one finds the second
  to last reporting 14 minutes earlier `observed that model was finished,
  waiting tasks completion...`

singelton long durations during cooldown - REASON?!
```
2023-07-16 10:48:07,737 processed 1000 events in 7.504578s. 118485 left in queue
2023-07-16 10:48:19,034 processed 1000 events in 9.287830s. 117485 left in queue
2023-07-16 10:48:46,323 processed 1000 events in 18.624433s. 115485 left in queue
2023-07-16 10:48:57,499 processed 1000 events in 8.231568s. 114485 left in queue
2023-07-16 10:55:10,196 processed 1000 events in 7.288574s. 54485 left in queue
2023-07-16 10:55:49,015 processed 1000 events in 23.923132s. 51485 left in queue
2023-07-16 11:01:14,219 processed 1000 events in 12.348842s. 1485 left in queue
```

#### our branch

we run on branch `simple-snapshot-investigation-rebase` of my own fork, commit
`7cf31473adb`, in a komodoenv based on bleeding (different commit compared to
above - just a few formal changes to test config files, and rebased onto main
of equinor fork)

this gives us ee logs where

- we have at most 104k events left in queue
- first batches ran in under 1 second
- queue buildup had times between 1 and 2 seconds
- queue cooldown consistently at < 0.4 seconds
- final batch 0.15 seconds
- running time according to CLI: 7 minutes, logs agree

### GUI

we run with the gui, changing to ensemble experiment and hitting go immediately

#### bleeding

we run with komodo bleeding (which was green, btw, awesome), which has ert main
at commit `5e3164269`.

**TODO** note results!

#### our branch

we run on branch `simple-snapshot-investigation-rebase` of my own fork, commit
`7cf31473adb`, in a komodoenv based on bleeding (different commit compared to
above - just a few formal changes to test config files, and rebased onto main
of equinor fork)

this gives us ee logs where

- we have at most 109k events left in queue
- first batches ran in under 1 second
- queue buildup had times between 1 and 3 seconds
- queue cooldown consistently at < 0.4 seconds (one outlier at 0.43)
- final batch 0.24 seconds
- four minutes between last job queue SUCCESS/`ensemble finished normally` in
  ee logs and app/logs finishing
- running time according to GUI: 7 minutes 40 seconds, logs agree

**Comment by pinkwah** [comment] 2023-07-20 10:58
User on Yammer has reported this too: https://web.yammer.com/main/org/statoil.com/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMjM2MzQyMTQyNDY4OTE1MiJ9

**Comment by hnformentin** [comment] 2023-08-17 05:09
User on Slack reported this too:
https://equinor.slack.com/archives/CDPJULWR4/p1692083517380579

**Comment by valentin-krasontovitsch** [comment] 2023-08-17 13:22
reopening until we have confirmed working through user tests

**Comment by valentin-krasontovitsch** [comment] 2023-08-29 06:30
Just to summarize here a bit our findings so far since merging and releasing this in komodo - we have several users that have run heavy (many realz) workflows, and they finished successfully (besides some RMS issues, that we suspect are related to lack of memory).

we have one or two users running stuff in azure, and they report failures - cf. [the slack thread](https://equinor.slack.com/archives/C01MCMWD075/p1692943819913559) [INTERNAL LINK].

to just have the relevant observations here as well:

> * they seem to be running with 100 realz
> * we have long processing times for just a handful of events in the beginning of iter-0 (does not lead to timeouts):
> ```
> 2023-08-22 09:32:45,036 processed 8 events in 4.450264s. 0 left in queue
> 2023-08-22 09:32:55,920 processed 4 events in 7.749988s. 0 left in queue
> 2023-08-22 09:33:08,870 processed 1 events in 10.502106s. 0 left in queue
> 2023-08-22 09:33:34,052 processed 2 events in 22.767731s. 0 left in queue
> 2023-08-22 09:34:33,443 processed 9 events in 56.638394s. 0 left in queue
> 2023-08-22 09:35:16,219 processed 7 events in 39.758926s. 0 left in queue
> 2023-08-22 09:35:24,024 processed 16 events in 5.047750s. 0 left in queue
> ```
>
> * further processing is fast, no errors or timeouts
> * come iter-1, we get long processing again, just one instance:
>
> ```
> 14:24:29,328 Evaluator is done
> 14:24:34,334 connecting to new monitor...
> 14:25:17,050 Started evaluator, joining until shutdown
> 14:25:17,083 connected
> 14:25:19,009 processed 101 events in 0.007326s. 0 left in queue
> 14:25:22,372 no events to be processed in queue
> 14:25:26,195 no events to be processed in queue
> 14:25:42,516 processed 2 events in 12.302223s. 0 left in queue
> 14:28:48,042 connection closed error: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
> 14:28:48,050 connecting to new monitor...
> 14:28:48,736 processed 6 events in 184.077428s. 0 left in queue
> ```
> * finally we get a bunch of connection closed errors, the usual, until
>   the queue fails to send, taking everything down

this last occurence is rather frustrating - one is tempted to explain the long processing times with slower disk and / or network performance, yet i am not aware of anything disk intense that might be happening at the same time as this error occured (at the beginning of iteration 1). also, after our changes (moving the batching processor into its own thread), we would expect that based on our understanding of the python scheduler, the ensemble evaluator should not experience trouble even though the dispatcher gets busy. it seems our mental model is still faulty.

**Comment by valentin-krasontovitsch** [comment] 2023-08-30 08:38
another potentially important note that i don't want to get lost in my private notes - user at johan sverdrup told me that they had fewer difficulties in running an ensemble experiment with 200 realizations when they reduced the number of parameters, using `../input/distributions` rather than `gen_kw_init_all.txt`, used like this in config (name included in `<GEN_KW_INIT_NAME>`:
```
GEN_KW INIT_FILES ../input/templates/gen_kw.tmpl dummy.txt <GEN_KW_CONFIG_INIT> INIT_FILES:../input/distributions/<CASE>/<GEN_KW_INIT_NAME>%d.txt
```

i don't have more details written down, if anybody ever wants to investigate this remark (and doesn't know who the user in question is), ping me

**Comment by xjules** [comment] 2023-10-20 10:25
Closing this issue due to the good performance of running 300 realizations described in more detail [here](https://github.com/equinor/scout/issues/903)

**Closed by xjules** 2023-10-20 10:25 UTC
Labels: bug
