### ISSUE TITLE
Run PrefectEnsemble on the azure cluster

### ISSUE THREAD

**Issue by DanSava** [equinor/ert#1305] opened 2021-01-20 14:36 UTC
Currently PrefectEnsemble uses a storage drive that supports only a shared disk assumption. 

Expend the storage drive functionality to support not shared disk storage and retrieval of resources

**Comment by markusdregi** [comment] 2021-01-28 16:52
Duplicate of #1334

**Closed by markusdregi** 2021-01-28 16:52 UTC
Labels: user request
