### ISSUE TITLE
Increasing size of ert running progress window gives QXcbConnection errors

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#5350] opened 2023-05-08 12:03 UTC
**Describe the bug**
When running some simulation in ert, (enabling the detailed view - necessary?), and increasing the size of the run simulations window, we get logs in the command line:

```
qt.qpa.xcb: QXcbConnection: XCB error: 13 (BadGC), sequence: 16104, resource id: 0, major code: 130 (Unknown), minor code: 3
qt.qpa.xcb: QXcbConnection: XCB error: 13 (BadGC), sequence: 16133, resource id: 0, major code: 130 (Unknown), minor code: 3
...
```

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui my_config.ert`
3. Run experiment (IES/Smoother/ESMDA/Test)
4. …

**Environment**
 - OS: ubuntu 22.04
 - ERT: main
 - Python version: 3.10
 - Remote/HPC execution involved: no

**Comment by oyvindeide** [comment] 2023-12-05 12:33
Not able to reproduce this on my mac or on rhel7, so will close this issue.

**Closed by oyvindeide** 2023-12-05 12:33 UTC
Labels: bug
