### ISSUE TITLE
es_mda does not finish

### ISSUE THREAD

**Issue by berland** [equinor/ert#6056] opened 2023-09-06 07:52 UTC
**Describe the bug**
The nightly test runs with `es_mda` do not finish.

**To reproduce**
Example failed run: https://github.com/equinor/komodo-releases/actions/runs/6091573655/job/16528849631

Fetch the artifact from https://github.com/equinor/komodo-releases/suites/15836268583/artifacts/904486922

All realizations are finished:
```
$ grep Realization ert-log-hm_analysis-ert-2023-09-05T1514.txt  | grep complete | wc -l
200
```
The last lines of  the ert-log file says:

```
$ tail -n 2 ert-log-hm_analysis-ert-2023-09-05T1514.txt 
2023-09-05 18:19:00,974 - ert.job_queue.job_queue_node - Thread-203 - INFO - Realization: 47 complete, starting to load results
2023-09-05 18:19:01,495 - ert.config.summary_config - Thread-203 - WARNING - Realization: 47, load warning: 1 inconsistencies in time map, first: Time mismatch for response time: 2003-02-02 00:00:00, last: Time mismatch for response time: 2003-02-02 00:00:00 from: /scratch/oompf/hm-tutorial-runs/tmp.wnY3sBzuOo/hm_analysis/f_scout_ci/hm_analysis/realization-47/iter-3/eclipse/model/HM_ANALYSIS-47.UNSMRY
```
The ensemble-evaluator log repeats this every fifth second until the Github runner times  out:
```
2023-09-05 21:13:42,954 - ert.ensemble_evaluator.dispatch - ert_ee_batch_dispatcher - DEBUG - no events to be processed in queue
2023-09-05 21:13:44,957 - ert.ensemble_evaluator.dispatch - ert_ee_batch_dispatcher - DEBUG - no events to be processed in queue
```

**Expected behaviour**
Ert should finish when it is done analyzing the last iteration.

**Environment**
 - OS: [e.g. RHEL7]
 - ERT/Komodo release: [e.g. 2.18 or 2020.12.00]
 - Python version
 - Remote/HPC execution involved: [yes|no]

**Additional context**

**Comment by xjules** [comment] 2023-09-06 13:36
This looks like the error caused by `forking` commit, which has been reverted since. We need to double-check how this run will go: https://github.com/equinor/komodo-releases/actions/runs/6095716349/job/16541678762

**Comment by xjules** [comment] 2023-09-25 10:35
I have not seen this "not finished" onprem nodes since. Shall we then close this one @berland?

**Closed** 2023-09-29 11:45 UTC
Labels: bug
