### ISSUE TITLE
Error sometimes on starting drogon

### ISSUE THREAD

**Issue by mortalisk** [equinor/ert#5299] opened 2023-04-26 12:47 UTC
**Describe the bug**
Got this in log when starting drogon on testing.

```
2023-04-26 14:01:01,376 - ert.__main__ - MainThread - ERROR - ERT crashed unexpectedly with "Signal 2 received."
Traceback (most recent call last):
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib64/python3.8/site-packages/ert/__main__.py", line 556, in main
    with start_ert_server(args.mode), ErtPluginContext() as context:
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/plugins/plugin_manager.py", line 243, in __init__
    self.plugin_manager = ErtPluginManager(plugins=plugins)
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/plugins/plugin_manager.py", line 34, in __init__
    self.load_setuptools_entrypoints(_PLUGIN_NAMESPACE)
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib/python3.8/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib/python3.8/site-packages/semeio/workflows/ahm_analysis/ahmanalysis.py", line 11, in <module>
    import xtgeo
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib64/python3.8/site-packages/xtgeo/__init__.py", line 118, in <module>
    from xtgeo.surface import regular_surface
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib64/python3.8/site-packages/xtgeo/surface/__init__.py", line 6, in <module>
    from xtgeo.surface.regular_surface import RegularSurface
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib64/python3.8/site-packages/xtgeo/surface/regular_surface.py", line 57, in <module>
    from . import (
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib64/python3.8/site-packages/xtgeo/surface/_regsurf_grid3d.py", line 11, in <module>
    from xtgeo.grid3d import _gridprop_lowlevel
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib64/python3.8/site-packages/xtgeo/grid3d/__init__.py", line 13, in <module>
    from .grid import Grid
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib64/python3.8/site-packages/xtgeo/grid3d/grid.py", line 18, in <module>
    from . import (
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib64/python3.8/site-packages/xtgeo/grid3d/_grid_etc1.py", line 16, in <module>
    from xtgeo.xyz.polygons import Polygons
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib64/python3.8/site-packages/xtgeo/xyz/__init__.py", line 6, in <module>
    from xtgeo.xyz._xyz import XYZ
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib64/python3.8/site-packages/xtgeo/xyz/_xyz.py", line 8, in <module>
    from . import _xyz_oper
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib64/python3.8/site-packages/xtgeo/xyz/_xyz_oper.py", line 8, in <module>
    from scipy.interpolate import UnivariateSpline, interp1d
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib64/python3.8/site-packages/scipy/interpolate/__init__.py", line 166, in <module>
    from ._interpolate import *
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib64/python3.8/site-packages/scipy/interpolate/_interpolate.py", line 11, in <module>
    import scipy.special as spec
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib64/python3.8/site-packages/scipy/special/__init__.py", line 649, in <module>
    from . import _ufuncs
  File "<frozen importlib._bootstrap>", line 389, in parent
  File "/prog/res/komodo/2023.05.b3-py38-rhel7/root/lib64/python3.8/site-packages/ert/services/_base_service.py", line 45, in cleanup_service_files
    raise OSError(f"Signal {signum} received.")
OSError: Signal 2 received.
2023-04-26 14:01:01,439 - root - MainThread - INFO - Peak memory use: 177092 kB
```

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui my_config.ert`
3. Run experiment (IES/Smoother/ESMDA/Test)
4. …

**Expected behaviour**

**Screenshots**

**Environment**
 - OS: [e.g. RHEL7]
 - ERT/Komodo release: [e.g. 2.18 or 2020.12.00]
 - Python version
 - Remote/HPC execution involved: [yes|no]

**Additional context**

**Comment by sondreso** [comment] 2023-05-08 07:13
@hnformentin Have you observed this with the testing release?

**Comment by hnformentin** [comment] 2023-05-12 06:44
I think that the issue is not complete regarding how to reproduce.
I downloaded the latest Drogon and source komodo 2023.05.01.
Iteration 0 is almost finished. two realizations failed with:
/prog/roxar/rms/rms: line 1239: 208311 Segmentation fault      (core dumped) "${APPLCMD}" ${USE_MESA} ${APPLOPTS}
Traceback (most recent call last):
  File "/prog/res/komodo/2023.05.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/share/ert/forward-models/res/script/rms.py", line 333, in <module>
    run(
  File "/prog/res/komodo/2023.05.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/share/ert/forward-models/res/script/rms.py", line 321, in run
    run_object.run()
  File "/prog/res/komodo/2023.05.01-py38-rhel7/root/lib64/python3.8/site-packages/ert/shared/share/ert/forward-models/res/script/rms.py", line 175, in run
    raise RMSRunException(f"The RMS run failed with exit status: {exit_status}")
__main__.RMSRunException: The RMS run failed with exit status: 139

**Comment by oyvindeide** [comment] 2023-05-12 07:57
Did ert crash though? Sounds like you got past the point mentioned in the issue. I will close this then, if you reproduce though, feel free to reopen.

**Closed by oyvindeide** 2023-05-12 07:57 UTC
Labels: bug

**Comment by hnformentin** [comment] 2023-05-12 08:47
The simulations completed just now with no error.
Thanks for sparing me the activity of closing it :-)
