### ISSUE TITLE
Yaml configuration file

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#191] opened 2018-11-14 19:39 UTC

**Comment by markusdregi** [comment] 2018-11-14 19:40
Depends on https://github.com/Statoil/libres/issues/238

**Comment by markusdregi** [comment] 2018-11-16 13:17
We should start by revising how this was done in the existing format together with @joakim-hove.

**Comment by markusdregi** [comment] 2018-11-16 13:18
Needs https://github.com/Statoil/libres/issues/238

**Comment by oyvindeide** [comment] 2020-12-17 09:56
Will close this as a duplicate of several other issues, filter on [configuration](https://github.com/equinor/ert/labels/Configuration).

**Closed by oyvindeide** 2020-12-17 09:56 UTC
Labels: Configuration, epic, ert3, need-adequate-description, user request
