### ISSUE TITLE
QT-warning when opening Event Viewer

### ISSUE THREAD

**Issue by berland** [equinor/ert#3272] opened 2022-04-20 10:39 UTC
**Describe the bug**
When opening the "Event viewer", warnings/errors from QT occur in the terminal window:
```
QTextCursor::setPosition: Position '1' out of range
QTextCursor::setPosition: Position '1' out of range
QTextCursor::setPosition: Position '1' out of range
QTextCursor::setPosition: Position '1' out of range
QTextCursor::setPosition: Position '1' out of range
```

This will repeat after a couple of seconds. There are no visual issues in the Event viewer itself, and ERT progresses normally.

**To Reproduce**
1. Install ert from main branch
2. `cd test-data/local/snake_oil`
3. `ert gui snake_oil.ert`
4. Click "Event viewer"
5. Observe messages in terminal window

**Expected behavior**
Error messages not to appear.

**Enviromment**
 - OS: RHEL7
 - ERT ca 2.34. Also confirmed in Komodo bleeding on 2022-04-20.
 - Python version 3.6
 - Remote/HPC execution involved: no

**Additional context**

**Comment by berland** [comment] 2022-04-21 12:52
```
(3.6) [havb@be-lx895926:~]$ pip freeze
absl-py==1.0.0
aiofiles==0.8.0
aiohttp==3.8.1
aiosignal==1.2.0
alabaster==0.7.12
alembic==1.7.6
aniso8601==7.0.0
ansicolors==1.1.8
anyio==3.5.0
appdirs==1.4.4
asgiref==3.4.1
astor==0.8.1
astroid==2.11.2
asttokens==2.0.5
async-exit-stack==1.0.1
async-generator==1.10
async-timeout==4.0.2
asynctest==0.13.0
attrs==19.3.0
autoapi==2.0.1
Babel==2.9.1
backcall==0.2.0
beartype==0.9.1
black==22.3.0
bleach==4.1.0
Brotli==1.0.9
build==0.7.0
cached-property==1.5.2
certifi==2021.10.8
cffi==1.15.0
cfgv==3.3.1
charset-normalizer==2.0.11
check-manifest==0.47
click==8.0.4
cloudevents==1.2.0
cloudpickle==2.0.0
cmake-format==0.6.13
cmakelang==0.6.13
ConfigArgParse==1.5.3
configsuite==0.6.6
contextlib2==21.6.0
contextvars==2.4
coverage==6.2
croniter==1.2.0
cryptography==36.0.1
cwrap==1.6.1
cycler==0.11.0
dash==2.3.1
dash-bootstrap-components==1.1.0
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-pivottable==0.0.2
dash-table==5.0.0
dask==2021.3.0
dask-jobqueue==0.7.3
dataclasses==0.8
decorator==5.1.1
defusedxml==0.7.1
deprecation==2.1.0
devtools==0.8.0
dill==0.3.4
disjoint-set==0.7.3
distlib==0.3.4
distributed==2021.3.0
distro==1.6.0
dnspython==2.2.0
docker==5.0.3
docutils==0.17.1
ecl==2.13.1
ecl-data-io==1.0.0
ecl2df @ file:///work/projects/ecl2df
-e git+ssh://git@github.com/equinor/ert@e2ba9353e8dc3bbf3c95015f4274227c156aa877#egg=ert
-e git+ssh://git@github.com/equinor/ert-storage@8bfdb80fd4cbaa62167b916f0fa3506527f928ee#egg=ert_storage
esbonio==0.11.0
et-xmlfile==1.1.0
-e git+ssh://git@github.com/Equinor/everest@b6d622328e840c6b69d100286a261ef5fb873eae#egg=everest
execnet==1.9.0
executing==0.8.2
fastapi==0.70.1
filelock==3.4.1
flake8==4.0.1
flaky==3.7.0
Flask==2.0.3
Flask-Caching==1.10.1
Flask-Compress==1.11
flask-talisman==1.0.0
fmu-ensemble==1.5.0
fmu-tools==1.9.0
frozenlist==1.2.0
future==0.18.2
graphene==2.1.9
graphene-sqlalchemy==2.3.0
graphlib-backport==1.0.3
graphql-core==2.3.2
graphql-relay==2.0.1
greenlet==1.1.2
grpcio==1.43.0
h11==0.12.0
h5py==3.1.0
hdf5plugin==3.2.0
HeapDict==1.0.1
httpcore==0.14.6
httpx==0.22.0
hypothesis==5.49.0
hypothesis-jsonschema==0.20.1
identify==2.4.4
idna==3.3
idna-ssl==1.1.0
imagesize==1.3.0
immutables==0.16
importlib-metadata==4.8.3
importlib-resources==5.2.3
iniconfig==1.1.1
ipython==7.16.3
ipython-genutils==0.2.0
isort==5.10.1
itsdangerous==2.0.1
jedi==0.17.2
Jinja2==3.0.3
joblib==1.1.0
jsonpath-ng==1.5.3
jsonschema==3.2.0
junit-xml==1.9
jupyter-core==4.9.2
jupytext==1.13.8
kiwisolver==1.3.1
lazy-object-proxy==1.7.1
Mako==1.1.6
Markdown==3.3.6
markdown-it-py==2.0.1
MarkupSafe==2.0.1
marshmallow==3.14.1
marshmallow-oneofschema==3.0.1
matplotlib==3.3.4
mccabe==0.6.1
mdit-py-plugins==0.3.0
mdurl==0.1.0
mock==4.0.3
msal==1.17.0
msgpack==1.0.3
multidict==5.2.0
multiprocess==0.70.12.2
mypy==0.931
mypy-extensions==0.4.3
nbformat==5.1.3
networkx==2.5.1
ninja==1.10.2.3
nodeenv==1.6.0
numexpr==2.8.1
numpy==1.19.5
odfpy==1.4.1
openpyxl==3.0.9
opm==2021.10
orjson==3.6.1
ortools==9.3.10497
packaging==21.3
pandas==1.1.5
parso==0.7.1
pathos==0.2.8
pathspec==0.9.0
pbr==5.8.0
pendulum==2.1.2
pep517==0.12.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.4.0
platformdirs==2.4.0
plotly==5.7.0
pluggy==1.0.0
ply==3.11
pox==0.3.0
ppft==1.6.6.4
pre-commit==2.17.0
prefect==0.15.13
-e git+ssh://git@github.com/equinor/PyPDM.git@ed9e0ee87989e891bb1c0cc7bef0a411ba243ea7#egg=proddata
progressbar2==3.55.0
promise==2.3
prompt-toolkit==3.0.27
protobuf==3.19.4
psutil==5.9.0
ptyprocess==0.7.0
py==1.11.0
pyarrow==6.0.1
pycallgraph==1.0.1
pycodestyle==2.8.0
pycparser==2.21
pydantic==1.9.0
pyflakes==2.4.0
pygls==0.11.3
Pygments==2.11.2
PyJWT==2.3.0
pylint==2.13.5
pyparsing==3.0.7
PyQt5==5.15.6
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.1
pyrsistent==0.18.0
pyscal==0.9.0
pyspellchecker==0.6.3
pytest==7.0.1
pytest-asyncio==0.16.0
pytest-console-scripts==1.3
pytest-cov==3.0.0
pytest-forked==1.4.0
pytest-httpserver==1.0.4
pytest-mock==3.6.1
pytest-qt==4.0.2
pytest-raises==0.11
pytest-repeat==0.9.1
pytest-runner==5.3.1
pytest-snapshot==0.8.1
pytest-subtests==0.6.0
pytest-timeout==2.1.0
pytest-xdist==2.5.0
python-box==5.4.1
python-dateutil==2.8.2
python-multipart==0.0.5
python-slugify==5.0.2
python-utils==3.1.0
pytz==2021.3
pytzdata==2020.1
PyYAML==5.4.1
QtPy==2.0.1
requests==2.27.1
rfc3986==1.5.0
rips==2021.10.2.1
RoffIO==0.0.2
rstcheck==3.3.1
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.6
Rx==1.6.1
SALib==1.4.5
schemathesis==1.3.4
scikit-build==0.14.0
scikit-learn==0.24.2
scipy==1.5.4
seaborn==0.11.2
-e git+https://7c009d171f082ee64bd5bcb19a2a858fe97079d3@github.com/tno-everest/seba.git@e3a43f4eb3cf5776abf8608cee5c11a99aeb7c95#egg=seba
segyio==1.9.7
semeio==1.4.3
setuptools-scm==6.4.2
Shapely==1.8.0
singledispatch==3.7.0
six==1.16.0
sniffio==1.2.0
snowballstemmer==2.2.0
sortedcontainers==2.4.0
Sphinx==4.3.2
sphinx-argparse==0.3.1
sphinx-autoapi==1.8.4
sphinx-autodoc-typehints==1.12.0
sphinx-rtd-theme==1.0.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-runcmd==0.2.0
sphinxcontrib-serializinghtml==1.1.5
sphinxcontrib.datatemplates==0.9.1
-e git+ssh://git@github.com/equinor/spinningjenny.git@bd87fbf918cc08cb9c672ead70930e7362be20e8#egg=spinningjenny
SQLAlchemy==1.4.31
starlette==0.16.0
stea==0.5.2
subscript @ git+https://github.com/equinor/subscript@002d47b8208d205924d0c09dcf3b0a394cbb0c52
tables==3.7.0
tabulate==0.8.9
tblib==1.7.0
tenacity==8.0.1
text-unidecode==1.3
threadpoolctl==3.1.0
tokenize-rt==4.2.1
toml==0.10.2
tomli==1.2.3
toolz==0.11.2
tornado==6.1
tox==3.24.5
tqdm==4.62.3
traitlets==4.3.3
treelib==1.6.1
typed-ast==1.5.2
typeguard==2.13.3
types-pkg-resources==0.1.3
types-python-dateutil==2.8.9
types-PyYAML==6.0.4
typing_extensions==4.0.1
Unidecode==1.3.2
urllib3==1.26.8
uvicorn==0.16.0
virtualenv==20.13.1
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.2.3
websockets==9.1
webviz-config==0.3.9
webviz-config-equinor==0.2.3
webviz-core-components==0.5.6
-e git+ssh://git@github.com/equinor/webviz-ert.git@05eb353db37725eab08405760442224b4ceb88d1#egg=webviz_ert
webviz-subsurface-components==0.4.11
Werkzeug==2.0.2
wrapt==1.13.3
xlrd==2.0.1
xlwt==1.3.0
xtgeo==2.17.1
yarl==1.7.2
zict==2.0.0
zipp==3.6.0
```

**Comment by oyvindeide** [comment] 2022-04-26 12:15
Which python version is this on? Was not able to install the above versions on 3.6 or 3.9

**Comment by oyvindeide** [comment] 2022-04-28 12:49
I was not able to reproduce this on a fresh installation with python 3.6 on RHEL7, and not able to replicate it on the above environment. I will close this issue as I am not able to reproduce it.

**Closed by oyvindeide** 2022-04-28 12:49 UTC
Labels: bug
