### ISSUE TITLE
FAILED ert3/engine/integration/test_engine.py::test_sensitivity_oat_run_and_export

### ISSUE THREAD

**Issue by frode-aarstad** [equinor/ert#3175] opened 2022-03-30 14:27 UTC
**Describe the bug**
Failing on Jenkins. unit-tests/ert/#1513 

komodoenv: /prog/res/komodo/2022.04.rc1-py36-rhel7/

```
E       ert_shared.port_handler.NoPortsInRangeException: No available ports in range range(51820, 51841).

/prog/res/komodo/2022.04.rc1-py36-rhel7/root/lib64/python3.6/site-packages/ert_shared/port_handler.py:84: NoPortsInRangeException

```

More output:

```
_____________________ test_sensitivity_oat_run_and_export ______________________

workspace_integration = <ert3.workspace._workspace.Workspace object at 0x7f4b9f1f8e48>
sensitivity_ensemble = PluggedEnsembleConfig(forward_model=ForwardModel(stage='evaluate_polynomial', driver='local'), input=(PluggedEnsembleI...', transformation=None),), output=(EnsembleOutput(record='polynomial_output'),), size=None, storage_type='ert_storage')
stages_config = StagesConfig(__root__=(Unix(name='evaluate_polynomial', input=mappingproxy(IndexedOrderedDict([('coefficients', Plugge...table_commands=(TransportableCommand(name='poly', location=PosixPath('poly.py'), mime='application/octet-stream'),)),))
sensitivity_oat_experiment_config = ExperimentConfig(type='sensitivity', algorithm='one-at-a-time', tail=0.99, harmonics=None, sample_size=None)
gaussian_parameters_config = ParametersConfig(__root__=[_ParameterConfig(name='coefficients', type='stochastic', distribution=_GaussianDistribution...gaussian', input=_GaussianInput(mean=0.0, std=1.0)), variables=_VariablesConfig(__root__=['a', 'b', 'c']), size=None)])

    @pytest.mark.integration_test
    @pytest.mark.requires_ert_storage
    def test_sensitivity_oat_run_and_export(
        workspace_integration,
        sensitivity_ensemble,
        stages_config,
        sensitivity_oat_experiment_config,
        gaussian_parameters_config,
    ):
        workspace = workspace_integration
        (workspace._path / _EXPERIMENTS_BASE / "sensitivity").mkdir(parents=True)
        experiment_run_config = ert3.config.ExperimentRunConfig(
            sensitivity_oat_experiment_config,
            stages_config,
            sensitivity_ensemble,
            gaussian_parameters_config,
        )
        with assert_clean_workspace(workspace):
            ert3.engine.run_sensitivity_analysis(
>               experiment_run_config, workspace, "sensitivity"
            )

/tmp/jenkins-komodo-f_scout_ci/workspace/unit-tests/ert/test-root/tests/ert_tests/ert3/engine/integration/test_engine.py:722: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/prog/res/komodo/2022.04.rc1-py36-rhel7/root/lib64/python3.6/site-packages/ert3/engine/_run.py:333: in run_sensitivity_analysis
    output_transmitters = ert3.evaluator.evaluate(ensemble)
/prog/res/komodo/2022.04.rc1-py36-rhel7/root/lib64/python3.6/site-packages/ert3/evaluator/_evaluator.py:102: in evaluate
    config = EvaluatorServerConfig(custom_port_range=custom_port_range)
/prog/res/komodo/2022.04.rc1-py36-rhel7/root/lib64/python3.6/site-packages/ert_shared/ensemble_evaluator/config.py:149: in __init__
    custom_range=custom_port_range, custom_host=custom_host
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

custom_host = None, custom_range = None, will_close_then_reopen_socket = False

    def find_available_port(
        custom_host: Optional[str] = None,
        custom_range: Optional[range] = None,
        will_close_then_reopen_socket: bool = False,
    ) -> Tuple[str, int, socket.socket]:
        """
        The default and recommended approach here is to return a bound socket to the
        caller, requiring the caller to keep the socket-object alive as long as the
        port is needed.
    
        If the caller for some reason closes the returned socket there is no guarantee
        that it can bind again to the same port for two reasons:
        1) the underlying socket can be in TIME_WAIT meaning that it is closed
        but port is not ready to be re-bound yet, and 2) some other process managed to
        bind the port before the original caller gets around to re-bind.
    
        Thus, we expect clients calling find_available_port() to keep the returned
        socket-object alive and open as long as the port is needed. If a socket-object
        is passed to other modules like for example a websocket-server, use dup() to
        obtain a new Python socket-object bound to the same underlying socket (and hence
        the same port). That way, even if the other module closes its given socket-
        object, the port is still reserved and bound by the original socket-object.
    
        See e.g. implementation and comments in EvaluatorServerConfig
    
        However, our PrefectEnsemble integrates with Dask and DaskScheduler which only
        accepts an integer port-argument, not a bound socket-object or even a port-range.
        For this reason it is believed that we must allow the close-and-rebind  -pattern,
        i.e. the SO_REUSEADDR flag may have to be set before binding the socket. If
        the client really wants this behaviour, specify the argument
    
            will_close_then_reopen_socket = true
    
        in the call, but be aware that issue (2) above becomes a lot more likely.
        Additionally, quite some unexpected behaviour is going on when this flag is used,
        as demonstrated in test_port_handler.py. In particular, it looks like on Linux,
        a port can be re-bound even if there is already a live socket bound to it.
    
        So use this flag with extreme caution and only when in the hour of utmost need!
        Ideally it should be removed.
        """
        current_host = custom_host if custom_host is not None else _get_ip_address()
        current_range = (
            custom_range if custom_range is not None else range(51820, 51840 + 1)
        )
    
        if current_range.start == current_range.stop:
            ports = list(range(current_range.start, current_range.stop + 1))
        else:
            ports = list(range(current_range.start, current_range.stop))
    
        random.shuffle(ports)
        for port in ports:
            try:
                return (
                    current_host,
                    port,
                    _bind_socket(
                        host=current_host,
                        port=port,
                        will_close_then_reopen_socket=will_close_then_reopen_socket,
                    ),
                )
            except PortAlreadyInUseException:
                continue
    
>       raise NoPortsInRangeException(f"No available ports in range {current_range}.")
E       ert_shared.port_handler.NoPortsInRangeException: No available ports in range range(51820, 51841).

/prog/res/komodo/2022.04.rc1-py36-rhel7/root/lib64/python3.6/site-packages/ert_shared/port_handler.py:84: NoPortsInRangeException
```

**Comment by lars-petter-hauge** [comment] 2022-03-30 17:04
The issue is the narrow port range available for the test. Expanding this should fix the problem. We'll look into it!

**Comment by jondequinor** [comment] 2022-03-30 19:13
I think this should be configurable in both `run_sensitivity_analysis` and `run` in the ert3 engine, via providing `EvaluatorServerConfig` to those functions? What do you think?

**Comment by BjarneHerland** [comment] 2022-03-31 06:34
I'd suggest that we set default range really large (1k-64k or something) and rather specify the strict range when running the appliction in production.

**Comment by oysteoh** [comment] 2022-03-31 07:01
> I'd suggest that we set default range really large (1k-64k or something) and rather specify the strict range when running the appliction in production.

Probably a good idea injecting production range when needed instead of all tests injecting custom range yes. But first of all we need to make sure the port-range is injected everywhere it is used at least. Going into production with a port range not supported will not fly :)

**Comment by eivindjahren** [comment] 2022-09-15 12:54
Closing as related to ert3, which is no longer the direction taken by the project.

**Closed by eivindjahren** 2022-09-15 12:54 UTC
Labels: bug, flaky-test
