### ISSUE TITLE
Large amount of warnings "invalid node found"

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#3845] opened 2022-08-31 10:41 UTC
Running the drogon example with `ert vis` gives a large amount of warnings of the form:

```
** Warning:: invalid node found at offset:115091392 in datafile:/private/abc/drogon/drogon_20211115_12-12/resmod/ff/21.0.1/ert/output/storage/01_drogon_ahm/default_2/Ensemble/mod_3/PARAMETER.data_0 - data will be lost, node_size:0
```

This warning has been showing since at least march 2022 and I think the underlying assumption that there should never be invalid nodes is no longer correct. The warning should be removed.

**Comment by oysteoh** [comment] 2022-08-31 10:53
Fun fact - this has been present as stated in webviz-ert for a long time. It is also present in the august-release of komodo when running ert gui -> plot ( which is now utilizing the ert-api ). BUT - earlier releases of komodo where ert gui -> plotter is not utilizing the api - the warning is not printed. I'm not sure if this is related to our data pulled in a different ( and maybe faulty?)  way - or just because we see different logs/printouts in the terminal due to the fact we are running the plotter differently ( through native ert implementation vs through ert api )

**Comment by oysteoh** [comment] 2022-08-31 10:57
@hnformentin - here is the issue created from your finding. Do you have anything to add based on your testing please feel free to do so :smile:

**Comment by mortalisk** [comment] 2022-09-05 07:01
I think the actual storage in drogon is corrupted, so the warning might be valid?

**Comment by oysteoh** [comment] 2022-09-05 10:00
> I think the actual storage in drogon is corrupted, so the warning might be valid?

Then it is slightly weird the warning is present when we pull data through the api but not if you pull data as it was originally in the pyqt plotter ( ref my comment :arrow_up: :arrow_up: :arrow_up:  )

**Comment by mortalisk** [comment] 2022-09-05 11:10
I tried deleting storage, and running again the drogon_ahm.ert file. I don't see the warning any longer.

**Comment by oysteoh** [comment] 2022-09-05 12:16
Then i'll suggest we close the issue without any actions. Seems a bit weird to remove the warning message since this seems to actually by caused by some problems with the storage. I would rather know when this happens again by seeing this warning and then maybe try to pin down the cause of it instead of just remove it and never know... :man_shrugging:

**Comment by hnformentin** [comment] 2022-09-06 09:50
Good idea @mortalisk and agree @oysteoh ! I am just wondering if we could improve the warning message. For example, indicate that the storage folder may be corrupted and suggest the user to delete it before running again. Maybe other users have the same lack of knowledge as me and don't know about it :-)

**Comment by oyvindeide** [comment] 2023-01-27 15:18
This will be taken care of in the refactor of storage, so closing this.

**Closed by oyvindeide** 2023-01-27 15:18 UTC
Labels: bug
