### ISSUE TITLE
Possible behaviour change for general queue options

### ISSUE THREAD

**Issue by berland** [equinor/ert#8605] opened 2024-09-02 10:12 UTC
User reports indicate that we have introduced a behaviour change in the configuration for the combination of:

```
QUEUE_OPTION LOCAL MAX_RUNNING 12
MAX_RUNNING 2
```

where now the first line has precedence over the general option. Since the first line can be (and currently is) present in site-config, this leads to the users experiencing that their `MAX_RUNNING 2` configuration line has no effect.

**Comment by jonathan-eq** [comment] 2024-09-03 08:37
This was changed in https://github.com/equinor/ert/issues/8201

**Comment by jonathan-eq** [comment] 2024-09-03 08:44
I think this is an issue where similar options create confusion. `MAX_RUNNING` and `QUEUE_OPTION MAX RUNNING` are doing the same thing, so I suggest we remove the `QUEUE_OPTION` one. When the one that takes precedence (which could be either of them) are set in site-config, the user may try using the one that gets overturned.

**Comment by berland** [comment] 2024-09-03 09:53
The intention is to be able to have in your config f.ex.

```
MAX_RUNNING 4
QUEUE_OPTION LSF MAX_RUNNING 10000
```

Assuming no site-config, this should give MAX_RUNNING set to 4 for all other queue systems than LSF.

**Comment by jonathan-eq** [comment] 2024-09-03 12:50
Marked this as blocked as it needs further discussion if this is wanted behavior

**Comment by berland** [comment] 2024-09-03 12:52
> That seems to be the current behavior

Yup. The problem is that the user experience is quite bad if you only have 

```MAX_RUNNING 4```

in your config but the other line is set through site-config, then you will never understand why your keyword has no effect on the local queue.

**Comment by DanSava** [comment] 2024-09-03 13:03
I agree that the `MAX_RUNNING 2`  line has no effect in the case described above. It was designed not to overwrite the explicit queue option in the case above `QUEUE_OPTION LOCAL MAX_RUNNING 12`. 

I agree that this behaviour leads to confusion when considering options set through site-config that are not transparent to the user.

**Comment by sondreso** [comment] 2024-09-09 07:20
After a couple of discussions off-line the consensus seems to be that: 

- Options set by the user should always take precedence over what we have in the site-config. 
- If the users specifies both the global keyword and the specific queue option at the same time, the specific queue option should take precedence for that specific queue system, while the global should apply to all others.

**Closed** 2024-09-16 06:43 UTC
Labels: bug
